.github/workflows/check-actions.yaml
.github/workflows/lint.yaml
.github/workflows/tests.yaml

chore: add GH workflows

---

go.mod
go.sum
pkg/commands/root.go

feat: add root command

---

cmd/main.go
pkg/commands/version/command.go
pkg/version/version.go

Add version package and command.

feat: add version package and command

---

Makefile

Add make tests target.
Fixes #10

chore: add make tests target

---

.github/workflows/tests.yaml
.gitignore
Makefile

Add code covererage report.
Fixes #2

chore: add codecov

---

.github/workflows/tests.yaml

fix: codecov with forks

---

go.mod

chore: clean go mod

---

website/docs/tests/index.md
website/mkdocs.yaml

Add writing tests docs section.

docs: add writing tests docs section

---

.github/workflows/deploy.yaml
Makefile
website/apis/config.yaml
website/apis/markdown/members.tpl
website/apis/markdown/pkg.tpl
website/apis/markdown/type.tpl
website/docs/apis/chainsaw.v1alpha1.md
website/mkdocs.yaml

feat: add api docs

---

config/crds/chainsaw.kyverno.io_configurations.yaml
pkg/apis/v1alpha1/configuration.go
pkg/apis/v1alpha1/configuration_spec.go
pkg/commands/test/command.go
pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
website/apis/config.yaml
website/apis/markdown/members.tpl
website/apis/markdown/type.tpl
website/docs/apis/chainsaw.v1alpha1.md
website/mkdocs.base.yaml

feat: improve api docs

---

website/docs/overrides/home.html

fix: improve home

---

config/crds/chainsaw.kyverno.io_configurations.yaml
pkg/apis/v1alpha1/configuration_spec.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/commands/test/command.go
pkg/config/load.go
pkg/config/load_test.go
pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
testdata/config/custom-config.yaml
testdata/config/timeout-1m.yaml
website/docs/apis/chainsaw.v1alpha1.md
website/docs/commands/chainsaw_test.md

Fix : https://github.com/kyverno/chainsaw/issues/30

Add config elements

---

pkg/commands/test/command.go
pkg/utils/flag/flag.go

chore: add flag utils

---

website/docs/intro.md
website/docs/quick-start.md

chore: add quick start docs

---

pkg/commands/root_test.go
testdata/commands/root/help.txt

chore: add unit tests

---

website/docs/blog/.authors.yml
website/docs/blog/index.md
website/docs/blog/posts/posts/wip.md

chore: add blog post

---

pkg/config/load_test.go
pkg/test/load.go
pkg/test/load_test.go
testdata/test/bad-step.yaml
testdata/test/configmap.yaml
testdata/test/multiple.yaml
testdata/test/no-spec.yaml
testdata/test/no-steps.yaml
testdata/test/ok.yaml

feat: add test package

---

website/docs/quick-start.md

fix: quick start docs

---

pkg/commands/test/command.go

fix: flags

---

pkg/client/apply.go
pkg/runner/runner.go

Implement resource cleanup.
Fixes #72

feat: implement resource cleanup

---

pkg/runner/context.go
pkg/runner/namespacer/namespacer.go
pkg/runner/runner.go

feat: add namespacer

---

pkg/client/apply.go
pkg/runner/client/client.go
pkg/runner/context.go
pkg/runner/runner.go

Implement auto delete using client factory.
Fixes #79

feat: implement auto delete using client factory

---

pkg/client/key.go
pkg/runner/client/client.go
pkg/runner/runner.go

fix: improve logs

---

.vscode/launch.json
pkg/runner/client/client.go
pkg/runner/context.go
pkg/runner/logging/log.go
pkg/runner/logging/logger.go
pkg/runner/logging/step.go
pkg/runner/logging/test.go
pkg/runner/runner.go

feat: add loggers

---

config/crds/chainsaw.kyverno.io_tests.yaml
config/crds/chainsaw.kyverno.io_teststeps.yaml
pkg/apis/v1alpha1/apply.go
pkg/apis/v1alpha1/assert.go
pkg/apis/v1alpha1/error.go
pkg/apis/v1alpha1/test_step_spec.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
website/docs/apis/chainsaw.v1alpha1.md

Fix : https://github.com/kyverno/chainsaw/issues/87
Add better comments for the docs of the TestStepSpec

Add doc comments in TestStepSpec

---

pkg/runner/logging/log.go
pkg/runner/runner.go

fix: namespace flag

---

pkg/commands/test/command.go
pkg/commands/test/command_test.go
pkg/runner/context.go
pkg/runner/runner.go
pkg/runner/summary.go
testdata/commands/test/config_all_fields.txt
testdata/commands/test/default.txt
testdata/commands/test/with_regex.txt
testdata/commands/test/with_suppress.txt
testdata/commands/test/with_test_dirs.txt
testdata/commands/test/with_timeout.txt

fix: summary

---

pkg/runner/flags.go
pkg/runner/runner.go
pkg/runner/test.go

Refactor runner tests generation.

refactor: runner tests generation

---

pkg/runner/runner.go

fix: summary when test fails

---

pkg/commands/test/command.go
pkg/runner/runner.go

fix: remove exit code from runner

---

pkg/runner/context.go
pkg/runner/runner.go
pkg/runner/step.go

Implement step timeout part 1.

feat: implement step timeout part 1

---

pkg/commands/test/command.go
pkg/runner/runner.go
website/docs/quick-start.md

fix: exit code

---

website/docs/more/crds.md
website/docs/more/events.md
website/docs/more/ide-completion.md
website/mkdocs.yaml

Add more resources section docs.
Fixes #124

docs: add more resources section

---

Makefile
website/docs/tests/configuration.md
website/docs/tests/with-manifests.md
website/docs/tests/with-test-steps.md
website/docs/tests/with-test.md

chore: add docs files

---

README.md

chore: improve readme file

---

website/docs/tests/index.md

chore: add what is chainsaw docs

---

.goreleaser.yaml

chore: add goreleaser config

---

.goreleaser.yaml

chore: add kos to goreleaser config

---

.release-notes/_template.md

chore: add release-notes folder

---

README.md

chore: add more badges to readme

---

.docs/LABELS.md
.docs/RELEASE.md

chore: add dev docs

---

.github/workflows/check-actions.yaml
.github/workflows/codegen.yaml
.github/workflows/codeql.yaml
.github/workflows/deploy.yaml
.github/workflows/lint.yaml
.github/workflows/release.yaml
.github/workflows/tests.yaml

chore: harden workflows

---

go.mod
pkg/runner/operations/assert.go
pkg/runner/operations/diff.go

Return last errors in case of context timeout.

fix: return last errors in case of context timeout

---

pkg/runner/client/client.go
pkg/runner/runner.go
pkg/runner/step.go

Use FailNow instead of Fatal (to preserve custom logger).

fix: use FailNow instead of Fatal

---

pkg/commands/test/command.go
pkg/runner/context.go
pkg/runner/logging/log.go
pkg/runner/logging/step.go
pkg/runner/logging/test.go
pkg/runner/runner.go

feat: use clock interface

---

.github/workflows/deploy.yaml

chore: fix pages deployment

---

.github/workflows/check-actions.yaml
.github/workflows/codegen.yaml
.github/workflows/codeql.yaml
.github/workflows/deploy.yaml
.github/workflows/lint.yaml
.github/workflows/release.yaml
.github/workflows/tests.yaml

Fix workflow schemas in vscode.

Fix workflow schemas

---

.github/workflows/deploy.yaml

fix: deployment of gh pages

---

.crds/chainsaw.kyverno.io_tests.yaml
pkg/apis/v1alpha1/test_spec.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/runner/runner.go
website/docs/apis/chainsaw.v1alpha1.md

Add skip field to test.
Fixes #157

feat: add skip field to test

---

website/docs/tests/configuration.md

Fix : https://github.com/kyverno/chainsaw/issues/120

Add configuration docs

---

website/docs/tests/configuration.md

chore: add config docs

---

website/docs/tests/configuration.md
website/docs/tests/what-is-a-test.md
website/mkdocs.yaml

chore: add what is a test docs

---

website/docs/tests/with-manifests.md

Add manifests based test docs.
Fixes #121

chore: add manifests based test docs

---

.crds/chainsaw.kyverno.io_configurations.yaml
pkg/apis/v1alpha1/configuration_spec.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/commands/test/command.go
pkg/commands/test/command_test.go
pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
testdata/commands/test/config/config_all_fields.yaml
testdata/commands/test/config_all_fields.txt
testdata/commands/test/default.txt
testdata/commands/test/with_regex.txt
testdata/commands/test/with_repeat_count.txt
testdata/commands/test/with_suppress.txt
testdata/commands/test/with_test_dirs.txt
testdata/commands/test/with_timeout.txt
website/docs/apis/chainsaw.v1alpha1.md
website/docs/commands/chainsaw_test.md
website/docs/quick-start.md

we could support the suppress of logs later..... 
Fixes https://github.com/kyverno/chainsaw/issues/159

refactor : remove suppress 

---

website/docs/tests/with-manifests.md
website/docs/tests/with-test-steps.md
website/docs/tests/with-test.md

Add test step based syntax docs.
Fixes https://github.com/kyverno/chainsaw/issues/122

chore: add test step based syntax docs

---

website/docs/tests/with-manifests.md
website/docs/tests/with-test-steps.md
website/docs/tests/with-test.md

Add test based syntax docs.
Fixes #123

chore: add test based syntax docs

---

pkg/runner/operations/delete.go

fix: remove wrong logic

---

website/docs/tests/what-is-a-test.md

Fix : https://github.com/kyverno/chainsaw/issues/174

docs: what is test step 

---

pkg/runner/operations/assert.go
pkg/runner/operations/error.go

Fix error implementation.
Fixes #184

fix: error implementation

---

website/docs/tests/what-is-a-test.md

Close : https://github.com/kyverno/chainsaw/issues/185

docs: Add about the namespacer interface

---

pkg/runner/client/client.go
pkg/runner/context.go
pkg/runner/logging/logger.go
pkg/runner/operations/apply.go
pkg/runner/operations/assert.go
pkg/runner/operations/delete.go
pkg/runner/operations/error.go
pkg/runner/runner.go
pkg/runner/step.go

fix: logger

---

.release-notes/main.md
.release-notes/v0.0.1.md

release: v0.0.1

---

.goreleaser.yaml

fix: comment goreleaser ko target

---

.crds/chainsaw.kyverno.io_tests.yaml
pkg/apis/v1alpha1/test_spec.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/runner/runner.go
website/docs/apis/chainsaw.v1alpha1.md

Support config of parallel tests.
Fixes #183

feat: support config of parallel tests

---

pkg/runner/runner.go

Switch back to subtests.
Better summary from the testing package.

feat: switch back to subtests

---

.goreleaser.yaml

Add back kos in goreleaser config.

chore: add back kos in goreleaser config

---

.crds/chainsaw.kyverno.io_tests.yaml
.crds/chainsaw.kyverno.io_teststeps.yaml
pkg/apis/v1alpha1/apply.go
pkg/apis/v1alpha1/assert.go
pkg/apis/v1alpha1/delete.go
pkg/apis/v1alpha1/error.go
pkg/apis/v1alpha1/test_spec.go
pkg/apis/v1alpha1/test_step_spec.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
pkg/runner/step.go
website/docs/apis/chainsaw.v1alpha1.md

Add continue on error support.
Fixes #155

feat: add continue on error support

---

.github/workflows/release.yaml

chore: install ko

---

.release-notes/main.md
testdata/commands/root/help.txt
testdata/commands/version/help.txt

chore: update release notes

---

.crds/chainsaw.kyverno.io_configurations.yaml
.crds/chainsaw.kyverno.io_tests.yaml
.release-notes/main.md
pkg/apis/v1alpha1/configuration_spec.go
pkg/apis/v1alpha1/test_spec.go
pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/runner/runner.go
website/docs/apis/chainsaw.v1alpha1.md

Allow overriding test namespace.
Fixes #160

feat: allow overriding test namespace

---

.release-notes/_template.md
.release-notes/main.md
pkg/commands/kuttl/migrate/command.go

Kuttl migration error.
Fixes #176

fix: kuttl migration error

---

pkg/runner/operations/command.go
pkg/runner/operations/command_output.go
pkg/runner/step.go

fix: command timeout cancel

---

pkg/runner/logging/l.go
pkg/runner/logging/log.go
pkg/runner/logging/logger.go

fix: remove callsite from logs

---

.crds/chainsaw.kyverno.io_configurations.yaml
.release-notes/main.md
pkg/apis/v1alpha1/configuration_spec.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/commands/kuttl/migrate/command.go
pkg/commands/test/command.go
pkg/config/load_test.go
pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
pkg/runner/flags.go
testdata/commands/test/config_all_fields.txt
testdata/commands/test/default.txt
testdata/commands/test/with_regex.txt
testdata/commands/test/with_repeat_count.txt
testdata/commands/test/with_suppress.txt
testdata/commands/test/with_test_dirs.txt
testdata/commands/test/with_timeout.txt
website/docs/apis/chainsaw.v1alpha1.md
website/docs/commands/chainsaw_kuttl_migrate.md
website/docs/commands/chainsaw_test.md

Improve kuttl migrate command.

fix: improve kuttl migrate command

---

.release-notes/main.md

chore: release notes

---

website/docs/install.md

Closes : https://github.com/kyverno/chainsaw/issues/191

feat: Add how to Use docker image

---

website/docs/tests/what-is-a-test.md
website/docs/tests/with-test-steps.md

Fix : https://github.com/kyverno/chainsaw/issues/233
Fix : https://github.com/kyverno/chainsaw/issues/237

docs: v0.0.2 milestone

---

website/docs/commands/chainsaw_kuttl_migrate.md
website/docs/migration/kuttl_migrate.md

docs : Add kuttl-migrate docs

---

website/docs/tests/with-test.md

Fix : https://github.com/kyverno/chainsaw/issues/236
Fix : https://github.com/kyverno/chainsaw/issues/238

docs: Update the Test Doc 

---

website/docs/blog/posts/chainsaw.md
website/docs/blog/posts/wip.md
website/docs/intro.md
website/docs/more/kuttl-migration.md
website/mkdocs.yaml

fix: kuttl migration guide

---

.crds/chainsaw.kyverno.io_tests.yaml
.crds/chainsaw.kyverno.io_teststeps.yaml
pkg/apis/v1alpha1/command.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
pkg/runner/collect.go
pkg/runner/operations/exec.go
website/docs/apis/chainsaw.v1alpha1.md
website/docs/tests/collectors/commands.md
website/docs/tests/collectors/events.md
website/docs/tests/collectors/index.md
website/docs/tests/collectors/pod-logs.md
website/docs/tests/collectors/scripts.md
website/docs/tests/configuration.md
website/docs/tests/what-is-a-test.md
website/docs/tests/with-test-steps.md
website/docs/tests/with-test.md
website/mkdocs.yaml

Add collector docs.
Fixes #234

chore: add collector docs

---

pkg/version/version.go
website/docs/quick-start.md
website/docs/tests/what-is-a-test.md

chore: docs nits

---

.release-notes/main.md
.release-notes/v0.0.2.md

release: v0.0.2

---

go.mod
go.sum
pkg/discovery/discovery.go

fix: use slices package

---

.release-notes/v0.0.2.md

chore: fix typo in release notes

---

pkg/match/match_test.go

Fix : https://github.com/kyverno/chainsaw/issues/261

test: Match Unit Test

---

pkg/resource/load_test.go

Fix : https://github.com/kyverno/chainsaw/issues/260

test: Fix the Resource Testing

---

pkg/client/client_test.go

chore: use data driven test

---

pkg/client/client.go
pkg/runner/client/client.go

Reduce client interface scope.

refactor: reduce client interface scope

---

pkg/runner/client/client.go
pkg/runner/client/client_test.go

Add runner client tests.
Fixes #271

chore: add runner client tests

---

pkg/runner/timeout_test.go

chore: add timeout tests

---

pkg/runner/logging/l.go
pkg/runner/logging/logger.go
pkg/runner/logging/logger_test.go
pkg/runner/logging/mock.go

Fix : https://github.com/kyverno/chainsaw/issues/270

test : runner/logging package

---

pkg/runner/client/mock.go
pkg/runner/namespacer/namespacer.go
pkg/runner/namespacer/namespacer_test.go

chore: improve namespacer tests

---

pkg/runner/logging/logger_test.go
pkg/runner/logging/mock.go

Fix fake clock in logger tests.

chore: fix fake clock in logger tests

---

pkg/apis/v1alpha1/test_spec.go
pkg/apis/v1alpha1/test_step_spec.go

fix: timeouts api

---

pkg/runner/collect.go
pkg/runner/collect_test.go
pkg/runner/skip_delete.go
pkg/runner/skip_delete_test.go
pkg/runner/step.go

chore: add runner tests

---

pkg/client/key.go
pkg/client/key_test.go
pkg/runner/logging/l.go
pkg/runner/logging/logger_test.go

fix: unit tests

---

pkg/runner/collect_test.go

fix: tests

---

.release-notes/main.md
pkg/runner/step.go

Fix exec collector not invoked.
Fixes #297

fix: exec collector not invoked

---

pkg/commands/test/command.go
pkg/runner/step.go
pkg/runner/timeout.go
website/docs/commands/chainsaw_test.md

fix: improve timeouts

---

pkg/client/key_test.go
pkg/client/patch.go
pkg/client/patch_test.go
pkg/runner/operations/apply.go

chore: add more client tests

---

pkg/commands/docs/command_test.go
pkg/commands/root.go
pkg/commands/root/command.go
pkg/commands/root/command_test.go
testdata/commands/docs/help.txt
testdata/commands/help.txt
testdata/commands/root/help.txt

chore: add docs command help

---

pkg/commands/kuttl/command_test.go
testdata/commands/kuttl/help.txt

chore: add kuttl command tests

---

pkg/commands/version/command_test.go
testdata/commands/version/help.txt

Improve version command tests.

chore: improve version command tests

---

pkg/commands/test/command_test.go
testdata/commands/test/all_flags.txt

Add test command all flags test.

chore: add test command all flags test

---

pkg/runner/logging/internal/logger.go
pkg/runner/logging/l.go
pkg/runner/logging/l_test.go
pkg/runner/logging/logger.go
pkg/runner/logging/mock.go
pkg/runner/logging/testing/logger.go
pkg/runner/operations/apply_test.go

chore: improve runner/logging tests

---

.crds/chainsaw.kyverno.io_tests.yaml
.crds/chainsaw.kyverno.io_teststeps.yaml
.release-notes/main.md
pkg/apis/v1alpha1/apply.go
pkg/apis/v1alpha1/assert.go
pkg/apis/v1alpha1/delete.go
pkg/apis/v1alpha1/error.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
pkg/runner/step.go
website/docs/apis/chainsaw.v1alpha1.md

Add timeout support at operation level.

feat: add timeout support at operation level

---

pkg/runner/logging/l_test.go
pkg/runner/operations/assert_test.go
pkg/runner/operations/delete_test.go
pkg/runner/operations/error_test.go
pkg/runner/operations/exec_test.go
pkg/runner/operations/mock.go

chore: improve logger tests

---

website/docs/install.md

Fix install docs, compile from sources.

fix: install docs - compile from sources

---

website/docs/tests/configuration.md

Timeouts docs.
Fixes #291
Fixes #318

chore: timeouts docs

---

pkg/runner/flags.go
pkg/runner/flags/flags.go
pkg/runner/flags/flags_test.go

chore: add runner flags unit tests

---

pkg/commands/test/command.go
pkg/runner/step.go
pkg/runner/timeout/timeout.go
pkg/runner/timeout/timeout_test.go

refactor: runner timeout code

---

pkg/runner/operations/apply.go
pkg/runner/operations/apply_test.go
pkg/runner/operations/assert.go
pkg/runner/operations/assert_test.go
pkg/runner/operations/client.go
pkg/runner/operations/delete.go
pkg/runner/operations/delete_test.go
pkg/runner/operations/error.go
pkg/runner/operations/error_test.go
pkg/runner/operations/exec.go
pkg/runner/operations/exec_test.go
pkg/runner/runner.go
pkg/runner/step.go

refactor: introduce runner client

---

pkg/runner/cleanup/skip.go
pkg/runner/cleanup/skip_test.go
pkg/runner/step.go

Create runner/cleanup package.

refactor: create runner/cleanup package

---

pkg/runner/internal/flags.go
pkg/runner/names/test.go
pkg/runner/names/test_test.go
pkg/runner/runner.go

refactor: create runner/names package

---

pkg/runner/run.go
pkg/runner/runner.go
pkg/runner/test_runner.go

refactor: introduce tests runner

---

.crds/chainsaw.kyverno.io_tests.yaml
pkg/apis/v1alpha1/test_spec_step.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
testdata/discovery/invalid-test-and-steps/chainsaw-test.yaml
testdata/discovery/test/chainsaw-test.yaml
testdata/test/bad-step.yaml
testdata/test/ok.yaml
website/docs/apis/chainsaw.v1alpha1.md

refactor: inline test step spec

---

pkg/runner/client/client.go
pkg/runner/client/client_test.go
pkg/runner/context.go
pkg/runner/logging/context.go
pkg/runner/operations/client.go
pkg/runner/processor/processor.go
pkg/runner/runner.go
pkg/runner/step.go
pkg/runner/test_runner.go
pkg/runner/timeout/timeout.go
pkg/runner/timeout/timeout_test.go

feat: switch to contextual logging

---

pkg/runner/logging/context.go
pkg/runner/operations/client.go
pkg/runner/processor/processor.go
pkg/runner/run.go
pkg/runner/runner.go
pkg/runner/step.go
pkg/runner/test_runner.go
pkg/runner/testing/context.go

feat: switch to contextual testing

---

pkg/runner/operation.go
pkg/runner/step_runner.go
pkg/runner/test_runner.go

refactor: introduce step runner

---

pkg/runner/operation_runner.go
pkg/runner/step_runner.go

refactor: introduce operation runner

---

.github/workflows/release.yaml

Add released image provenance.
Fixes #355

feat: add released image provenance

---

pkg/runner/operations/command_output_test.go
pkg/runner/operations/exec.go
pkg/runner/operations/exec_test.go

fix: expand command args

---

pkg/config/load.go
pkg/config/load_test.go

Fix : https://github.com/kyverno/chainsaw/issues/334

test: 100% Coverage pkg/config/

---

.github/workflows/action.yml

chore: improve action workflow

---

pkg/runner/cleanup/cleanup.go
pkg/runner/operations/apply.go
pkg/runner/operations/client.go
pkg/runner/operations/create.go
pkg/runner/processors/operation.go
pkg/runner/processors/step.go
pkg/runner/processors/test.go

fix: runner client

---

pkg/runner/logging/context.go
pkg/runner/logging/internal/logger.go
pkg/runner/logging/l.go
pkg/runner/logging/log.go
pkg/runner/operations/apply.go
pkg/runner/operations/apply_test.go
pkg/runner/operations/assert.go
pkg/runner/operations/assert_test.go
pkg/runner/operations/client.go
pkg/runner/operations/create.go
pkg/runner/operations/create_test.go
pkg/runner/operations/delete.go
pkg/runner/operations/delete_test.go
pkg/runner/operations/error.go
pkg/runner/operations/error_test.go
pkg/runner/operations/exec.go
pkg/runner/operations/exec_test.go

fix: add more contextual logging

---

.crds/chainsaw.kyverno.io_tests.yaml
.crds/chainsaw.kyverno.io_teststeps.yaml
pkg/apis/v1alpha1/operation.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/commands/kuttl/migrate/command.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
pkg/discovery/discovery_test.go
pkg/discovery/load.go
pkg/discovery/load_test.go
pkg/runner/processors/operation.go
pkg/step/load_test.go
pkg/test/load_test.go
testdata/discovery/invalid-test-and-steps/01-test.yaml
testdata/discovery/invalid-test-and-steps/chainsaw-test.yaml
testdata/discovery/steps-and-manifests/01-test.yaml
testdata/discovery/steps/01-test.yaml
testdata/discovery/test-and-steps/01-test.yaml
testdata/discovery/test/chainsaw-test.yaml
testdata/kuttl/01-step.chainsaw.yaml
testdata/step/custom-step.yaml
testdata/step/multiple.yaml
testdata/step/ok.yaml
testdata/step/with-catch.yaml
testdata/step/with-finally.yaml
testdata/test/custom-test.yaml
testdata/test/ok.yaml
website/docs/apis/chainsaw.v1alpha1.md

refactor: single file ref in operation

---

pkg/runner/operations/apply_test.go
pkg/runner/operations/assert_test.go
pkg/runner/operations/create_test.go
pkg/runner/operations/delete_test.go
pkg/runner/operations/error_test.go
pkg/runner/operations/read_test.go

chore: refactor operations tests

---

.release-notes/main.md
.release-notes/v0.0.4.md

release: v0.0.4

---

pkg/runner/operations/apply_test.go
pkg/runner/operations/assert_test.go
pkg/runner/operations/create_test.go
pkg/runner/operations/delete_test.go
pkg/runner/operations/diff.go
pkg/runner/operations/diff_test.go
pkg/runner/operations/error_test.go

Increased the coverage in the below files
apply.go
assert.go
diff.go

test: Coverage pkg/runner/operations

---

website/docs/tests/operations/assert.md
website/docs/tests/operations/error.md

chore: add assertion trees docs

---

pkg/runner/operations/assert.go
pkg/runner/operations/assert_test.go

Sort assert error messages to get predictable output.

fix: sort assert error messages

---

.golangci.yml

feat: verbose golang CI Linting

---

.crds/chainsaw.kyverno.io_tests.yaml
.crds/chainsaw.kyverno.io_teststeps.yaml
pkg/apis/v1alpha1/apply.go
pkg/apis/v1alpha1/create.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
pkg/runner/operations/apply.go
pkg/runner/operations/apply_test.go
pkg/runner/operations/client.go
pkg/runner/operations/create.go
pkg/runner/operations/create_test.go
pkg/runner/processors/operation.go
website/docs/apis/chainsaw.v1alpha1.md

fix : https://github.com/kyverno/chainsaw/issues/407

feat: Dry-run in Apply/Create

---

pkg/runner/operations/client.go
pkg/runner/processors/operation.go
pkg/runner/processors/step.go
pkg/runner/processors/test.go

refactor: Operation Client Naming

---

.crds/chainsaw.kyverno.io_tests.yaml
.crds/chainsaw.kyverno.io_teststeps.yaml
pkg/apis/v1alpha1/apply.go
pkg/apis/v1alpha1/create.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
pkg/runner/operations/apply/apply.go
pkg/runner/operations/apply/apply_test.go
pkg/runner/operations/client.go
pkg/runner/operations/create/create.go
pkg/runner/operations/create/create_test.go
pkg/runner/processors/operation.go
testdata/step/custom-step.yaml
testdata/test/custom-test.yaml
website/docs/apis/chainsaw.v1alpha1.md

Add checks in apply and create.

feat: add checks in apply and create

---

pkg/runner/operations/apply/apply.go
pkg/runner/operations/apply/apply_test.go
pkg/runner/operations/assert/assert.go
pkg/runner/operations/client.go
pkg/runner/operations/command/command.go
pkg/runner/operations/create/create.go
pkg/runner/operations/create/create_test.go
pkg/runner/operations/delete/delete.go
pkg/runner/operations/error/error.go
pkg/runner/operations/operation.go
pkg/runner/operations/script/script.go

fix: cleanup

---

pkg/client/dry_run.go
pkg/runner/operations/apply/apply.go
pkg/runner/operations/apply/apply_test.go
pkg/runner/operations/client.go
pkg/runner/operations/create/create.go
pkg/runner/operations/create/create_test.go

refactor: dry run client

---

pkg/runner/operations/client.go
pkg/runner/processors/operation.go
pkg/runner/processors/step.go
pkg/runner/processors/test.go

refactor: namespacer

---

pkg/runner/processors/test.go
pkg/runner/processors/tests.go
pkg/runner/run.go

refactor: processors

---

pkg/runner/client/client.go
pkg/runner/logging/l.go
pkg/runner/logging/l_test.go
pkg/runner/logging/log.go
pkg/runner/logging/log_test.go
pkg/runner/logging/logger.go
pkg/runner/logging/section.go
pkg/runner/logging/testing/fake_logger.go
pkg/runner/logging/testing/logger.go
pkg/runner/operations/apply/apply.go
pkg/runner/operations/assert/assert.go
pkg/runner/operations/assert/assert_test.go
pkg/runner/operations/command/command.go
pkg/runner/operations/create/create.go
pkg/runner/operations/delete/delete.go
pkg/runner/operations/delete/delete_test.go
pkg/runner/operations/error/error.go
pkg/runner/operations/error/error_test.go
pkg/runner/operations/internal/command_output.go
pkg/runner/operations/script/script.go
pkg/runner/processors/step.go
pkg/runner/processors/test.go
pkg/runner/processors/tests.go

refactor: logger

---

pkg/runner/operations/apply/apply.go
pkg/runner/operations/assert/assert.go
pkg/runner/operations/command/command.go
pkg/runner/operations/create/create.go
pkg/runner/operations/delete/delete.go
pkg/runner/operations/error/error.go
pkg/runner/operations/script/script.go
pkg/runner/processors/step.go

chore: more operations

---

pkg/runner/processors/step.go
pkg/runner/processors/test.go
pkg/runner/processors/tests.go

fix: cleanup timeout

---

pkg/runner/operations/apply/apply.go
pkg/runner/operations/assert/assert.go
pkg/runner/operations/create/create.go
pkg/runner/operations/delete/delete.go
pkg/runner/operations/error/error.go
pkg/runner/processors/step.go
pkg/runner/processors/test.go
pkg/runner/processors/tests.go

fix: namespacer

---

pkg/runner/operations/command/command.go
pkg/runner/operations/command/command_test.go
pkg/runner/operations/script/script.go
pkg/runner/operations/script/script_test.go
pkg/runner/processors/step.go

Fixes script and command should set the cwd.
Fixes #436

fix: script and command should set the cwd

---

go.mod
go.sum
pkg/commands/kuttl/migrate/command.go
testdata/kuttl/01-step.chainsaw.yaml
testdata/kuttl/01-step.yaml

feat: add kuttl commands migration

---

pkg/runner/operations/apply/apply.go
pkg/runner/operations/create/create.go
pkg/runner/operations/delete/delete.go

make code much more clear and readable format.

refactor: Operations

---

.github/workflows/deploy.yaml
Makefile
website/docs/overrides/main.html
website/mkdocs.base.yaml

chore: add mike docs support

---

.github/workflows/deploy.yaml

chore: fix mike docs

---

go.mod
go.sum

chore: bump kyverno-json

---

go.mod
go.sum

fix: bump kyverno-json

---

website/docs/quick-start.md
website/docs/tests/with-test-steps.md
website/docs/tests/with-test.md

Described how to use custom test file in 
Add docs about the raw resource.
No need for the dry-run docs as this is already covered in the options.

docs: Add Docs

---

website/docs/tests/with-test-steps.md
website/docs/tests/with-test.md

docs: fix changes

---

.release-notes/main.md
.release-notes/v0.0.6.md

release: v0.0.6

---

.release-notes/v0.0.6.md

chore: fix typo

---

website/docs/tests/operations/apply.md
website/docs/tests/operations/command.md
website/docs/tests/operations/create.md
website/docs/tests/operations/script.md

fix: check docs

---

.docs/RELEASE.md

chore: publishing docs doc

---

.github/workflows/docs-main.yaml
.github/workflows/docs-release.yaml

chore: rename docs workflows

---

pkg/step/load_test.go
pkg/test/load_test.go
pkg/validation/apply.go
pkg/validation/assert.go
pkg/validation/catch.go
pkg/validation/command.go
pkg/validation/create.go
pkg/validation/delete.go
pkg/validation/error.go
pkg/validation/events.go
pkg/validation/file_ref.go
pkg/validation/file_ref_or_resource.go
pkg/validation/finally.go
pkg/validation/object_reference.go
pkg/validation/operation.go
pkg/validation/pod_logs.go
pkg/validation/script.go
testdata/step/with-catch.yaml
testdata/step/with-finally.yaml
testdata/test/ok.yaml

complete programmatic validation.

feat: complete programmatic validation

---

.release-notes/main.md
pkg/discovery/discovery_test.go
pkg/discovery/load.go
pkg/discovery/load_test.go

Fixed discovery of manifests in the wrong order.

fix: discovery of manifests in the wrong order

---

.github/workflows/codeql.yaml

fix: codeql workflow

---

.release-notes/main.md
pkg/runner/operations/command/command.go
pkg/runner/operations/script/script.go
testdata/kuttl/01-step.chainsaw.yaml
testdata/kuttl/02-step.chainsaw.yaml

chore: add command and script log

---

pkg/runner/logging/section_test.go

test: 100% Coverage pkg/runner/logging

---

.release-notes/main.md
go.mod
pkg/runner/operations/apply/apply.go
pkg/runner/operations/apply/apply_test.go
pkg/runner/operations/command/command.go
pkg/runner/operations/create/create.go
pkg/runner/operations/create/create_test.go
pkg/runner/operations/delete/delete.go
pkg/runner/operations/script/script.go

Use bindings in checks.
Fixes #499

feat: use bindings in checks

---

pkg/validation/check_test.go
pkg/validation/expectations_test.go

Add missing validation unit tests.

chore: add missing validation unit tests

---

pkg/client/namespace.go
pkg/runner/check/expect.go
pkg/runner/cleanup/cleanup.go
pkg/runner/operations/apply/apply.go
pkg/runner/operations/apply/apply_test.go
pkg/runner/operations/create/create.go
pkg/runner/operations/create/create_test.go
pkg/runner/operations/delete/delete.go
pkg/runner/operations/delete/delete_test.go
pkg/runner/processors/step.go
pkg/runner/processors/test.go
pkg/runner/processors/tests.go

Add expectations unit tests.
Fixes #503

chore: add expectations unit tests

---

pkg/report/report.go
pkg/report/report_test.go
pkg/runner/processors/operation.go
pkg/runner/processors/step.go
pkg/runner/processors/test.go
pkg/runner/processors/tests.go
pkg/runner/run.go

fix : https://github.com/kyverno/chainsaw/issues/161

feat: Add report Part-2

---

pkg/runner/processors/step.go

fix: remove pod workaround

---

pkg/runner/processors/step.go

Fix termination graceful period.

fix: termination graceful period

---

.release-notes/main.md

chore: typo in release notes

---

website/docs/more/kuttl-migration.md
website/docs/tests/catch-finally/index.md
website/docs/tests/configuration.md
website/docs/tests/operations/apply.md
website/docs/tests/operations/check.md
website/docs/tests/operations/command.md
website/docs/tests/operations/create.md
website/docs/tests/operations/delete.md
website/docs/tests/operations/script.md

Update v0.0.7 docs.
Fixes #516

chore: update v0.0.7 docs

---

README.md

Add dedicated slack channel in readme.

chore: add dedicated slack channel in readme

---

README.md
ROADMAP.md

Add initial roadmap.
Fixes #534

docs: Roadmap.md

---

.release-notes/main.md
go.mod
go.sum
pkg/runner/check/check.go
pkg/runner/check/functions/env.go
pkg/runner/check/functions/functions.go

Allow extend kyverno-json function caller.

feat: allow extend kyverno-json function caller

---

.github/workflows/tests.yaml
testdata/e2e/config.yaml
testdata/e2e/quick-start/basic/chainsaw-test.yaml
testdata/e2e/quick-start/basic/configmap-assert.yaml
testdata/e2e/quick-start/basic/configmap.yaml
testdata/e2e/quick-start/inline/chainsaw-test.yaml
testdata/e2e/quick-start/inline/configmap-assert.yaml
testdata/e2e/quick-start/timeout/chainsaw-test.yaml

chore: add end to end tests

---

.crds/chainsaw.kyverno.io_tests.yaml
.crds/chainsaw.kyverno.io_teststeps.yaml
.release-notes/main.md
pkg/apis/v1alpha1/delete.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
pkg/runner/operations/delete/delete.go
pkg/runner/operations/delete/delete_test.go
pkg/runner/processors/step.go
pkg/runner/processors/test.go
pkg/runner/processors/tests.go
pkg/validation/delete.go
testdata/e2e/quick-start/delete/chainsaw-test.yaml
website/docs/apis/chainsaw.v1alpha1.md

Use expect in delete operation.
Fixes #530

feat: use expect in delete op

---

.crds/chainsaw.kyverno.io_tests.yaml
.crds/chainsaw.kyverno.io_teststeps.yaml
pkg/apis/v1alpha1/catch.go
pkg/apis/v1alpha1/finally.go
pkg/apis/v1alpha1/operation.go
pkg/apis/v1alpha1/test_spec.go
pkg/apis/v1alpha1/test_step_spec.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
testdata/e2e/quick-start/basic/chainsaw-test.yaml
website/docs/apis/chainsaw.v1alpha1.md

feat: add description fields

---

.release-notes/main.md
go.mod
go.sum
pkg/commands/generate/command.go
pkg/commands/generate/docs/command.go
pkg/commands/generate/docs/docs.tmpl
pkg/commands/root.go
testdata/commands/help.txt
testdata/e2e/quick-start/basic/README.md
testdata/e2e/quick-start/delete/README.md
testdata/e2e/quick-start/inline/README.md
testdata/e2e/quick-start/timeout/README.md
website/docs/commands/chainsaw.md
website/docs/commands/chainsaw_generate.md
website/docs/commands/chainsaw_generate_docs.md

Add command to generate test docs.

feat: add command to generate test docs

---

go.mod
pkg/client/patch_test.go
pkg/client/unstructured.go
pkg/client/unstructured_test.go
pkg/resource/load_test.go
pkg/runner/check/check.go
pkg/runner/check/functions/env.go
pkg/runner/internal/corpus_entry.go
pkg/runner/internal/test_deps.go
pkg/runner/logging/l.go
pkg/runner/logging/section.go
pkg/runner/logging/section_test.go
pkg/runner/logging/t_logger.go
pkg/runner/logging/testing/fake_t_logger.go
pkg/runner/operations/apply/apply_test.go
pkg/runner/operations/assert/assert_test.go
pkg/runner/operations/command/command_test.go
pkg/runner/operations/create/create_test.go
pkg/runner/operations/delete/delete_test.go
pkg/runner/operations/error/error_test.go
pkg/runner/operations/internal/read_test.go
pkg/runner/operations/script/script_test.go
pkg/validation/file_ref_or_resource._test.go

chore: replace interface by any

---

pkg/runner/operations/delete/delete.go

refactor: delete operation

---

.release-notes/main.md
Makefile
pkg/commands/generate/docs/docs.tmpl
testdata/e2e/examples/basic/README.md
testdata/e2e/examples/basic/chainsaw-test.yaml
testdata/e2e/examples/catch/README.md
testdata/e2e/examples/delete/README.md
testdata/e2e/examples/finally/README.md
testdata/e2e/examples/inline/README.md
testdata/e2e/examples/sleep/README.md
testdata/e2e/examples/timeout/README.md
website/docs/configuration/index.md
website/docs/jp/functions.md
website/docs/more/test-docs.md
website/jp/main.go
website/mkdocs.yaml

chore: update docs

---

.release-notes/main.md
pkg/runner/logging/l.go
pkg/runner/logging/section.go
pkg/runner/logging/section_test.go

Fix log output with multiple sections.

fix: log output with multiple sections

---

pkg/runner/run.go
pkg/runner/run_test.go

test: pkg/runner/run.go

---

.release-notes/main.md
pkg/runner/processors/cleaner.go
pkg/runner/processors/step.go
pkg/runner/processors/test.go

refactor: cleanup management

---

.crds/chainsaw.kyverno.io_configurations.yaml
.crds/chainsaw.kyverno.io_tests.yaml
.release-notes/main.md
pkg/apis/v1alpha1/configuration_spec.go
pkg/apis/v1alpha1/test_spec.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/commands/test/command.go
pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/runner/processors/cleaner.go
pkg/runner/processors/test.go
testdata/commands/test/help.txt
website/docs/apis/chainsaw.v1alpha1.md
website/docs/commands/chainsaw_test.md

feat: add cleanup delay support

---

.release-notes/main.md
pkg/commands/test/command.go
pkg/commands/test/command_test.go
pkg/utils/fs/check.go
testdata/commands/test/config/config_all_fields.yaml
testdata/commands/test/config_all_fields.txt
testdata/commands/test/with_test_dirs.txt

Check folders in test command and return error if one is not accessible.

fix: check folders in test command

---

testdata/e2e/examples/catch/README.md
testdata/e2e/examples/catch/chainsaw-test.yaml
testdata/e2e/examples/finally/README.md
testdata/e2e/examples/finally/chainsaw-test.yaml

fix: e2e test names

---

pkg/runner/logging/l.go

fix: improve log messages

---

.gitignore
.schemas/json/configuration-chainsaw-v1alpha1.json
.schemas/json/test-chainsaw-v1alpha1.json
Makefile

Add json schemas support.
Fixes #598

feat: add json schemas support

---

pkg/commands/migrate/kuttl/tests/command.go
pkg/commands/migrate/tests/command.go

Fix migration commands overwriting generated files.

fix: migration commands

---

.release-notes/main.md
.release-notes/v0.0.9.md

release: v0.0.9

---

pkg/discovery/discovery.go
pkg/discovery/load.go
pkg/discovery/load_test.go
testdata/discovery/multiple-tests/chainsaw-test.yaml

Add multiple tests in file support.

feat: add multiple tests in file support

---

pkg/resource/load.go
pkg/resource/load_test.go
pkg/utils/fs/discover_test.go

chore: add a couple unit tests

---

codecov.yml

chore: codecov config

---

pkg/resource/load.go

Fix error message in resource loading.

fix: error message in resource loading

---

.goreleaser.yaml

feat: add brew support

---

.release-notes/main.md
.release-notes/v0.0.1.md
website/docs/tests/index.md

Fix : https://github.com/kyverno/chainsaw/issues/619

docs: Parallel execution of Test

---

ADOPTERS.md

chore: add adopters

---

ADOPTERS.md

chore: Add  to Adopter list

---

.release-notes/main.md
.release-notes/v0.1.0.md

release: v0.1.0

---

.release-notes/main.md
pkg/commands/docs/command_test.go
pkg/commands/docs/options.go

Fix bad error check in docs command.
Fixes #631
Fixes #560

fix: bad error check in docs command

---

pkg/commands/generate/docs/catalog.tmpl
pkg/commands/generate/docs/command.go
testdata/e2e/examples/CATALOG.md

fix: catalog

---

pkg/commands/create/command.go
pkg/commands/create/command_test.go
pkg/commands/create/test/command.go
pkg/commands/create/test/command_test.go
pkg/commands/root.go
testdata/commands/create/help.txt
testdata/commands/create/test/help.txt
testdata/commands/create/test/out.txt
testdata/commands/help.txt
website/docs/commands/chainsaw.md
website/docs/commands/chainsaw_create.md
website/docs/commands/chainsaw_create_test.md

Add create test command.
Fixes #645

feat: add create test command

---

README.md

chore: add resources to the README

---

pkg/runner/processors/test.go
pkg/runner/processors/tests.go

Fix skip delete not applied to the test namespace.
Fixes #664

fix: skip delete not applied to the test namespace

---

pkg/commands/generate/docs/command.go
pkg/commands/test/command.go
pkg/discovery/discovery.go
pkg/discovery/discovery_test.go
testdata/commands/test/help.txt
website/docs/commands/chainsaw_test.md

feat: add labels selector support

---

.vscode/launch.json
pkg/runner/check/check.go
testdata/e2e/examples/assertion-tree/assert.yaml
testdata/e2e/examples/assertion-tree/chainsaw-test.yaml

fix: bindings being nil

---

website/mkdocs.yaml

fix: add missing docs

---

pkg/commands/create/test/command.go
testdata/commands/create/test/help.txt
website/docs/commands/chainsaw_create_test.md

Add description flag to create test command.

feat: add description flag to create test command

---

Makefile
pkg/data/data.go
pkg/data/data_test.go
pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
pkg/data/schemas/json/test-chainsaw-v1alpha1.json

Add json schemas to embedded data.

feat: add json schemas to embedded data

---

pkg/commands/export/command.go
pkg/commands/export/command_test.go
pkg/commands/export/schemas/command.go
pkg/commands/export/schemas/command_test.go
pkg/commands/root.go
testdata/commands/export/help.txt
testdata/commands/export/schemas/help.txt
testdata/commands/help.txt
testdata/e2e/examples/CATALOG.md
testdata/e2e/examples/assertion-tree/README.md
website/docs/commands/chainsaw.md
website/docs/commands/chainsaw_export.md
website/docs/commands/chainsaw_export_schemas.md
website/mkdocs.yaml

Add command to export json schemas.
Fixes #613

feat: add command to export json schemas

---

pkg/commands/assert/command.go
pkg/commands/root.go
testdata/commands/help.txt
website/docs/commands/chainsaw.md
website/docs/commands/chainsaw_assert.md
website/mkdocs.yaml

Add assert command.
Fixes #667

feat: add assert command

---

.release-notes/main.md
website/docs/resources.md
website/mkdocs.yaml

chore: add resources docs page

---

.release-notes/main.md
website/docs/more/crds.md
website/docs/more/events.md
website/mkdocs.yaml

chore: improve docs structure

---

.docs/RELEASE.md

Update release docs with GH action.

chore: update release docs with GH action

---

.github/workflows/check-actions.yaml
.github/workflows/codegen.yaml
.github/workflows/lint.yaml
.github/workflows/tests.yaml

Enable missing workflows on main.

chore: enable missing workflows on main

---

website/mkdocs.base.yaml

chore: enable docs strictness

---

.release-notes/main.md
.release-notes/v0.1.1.md

release: v0.1.1

---

website/docs/examples/basic.md
website/docs/examples/index.md

chore: add basic example

---

website/docs/examples/labels-selector.md
website/mkdocs.yaml

Add labels selector example.
Fixes #694

chore: add labels selector example

---

website/docs/examples/inline.md
website/mkdocs.yaml

chore: add inline resources example

---

website/docs/examples/assertion-tree.md
website/mkdocs.yaml

Add assertion-tree example.
Fixes #693

chore: add assertion-tree example

---

pkg/runner/check/functions/env.go
pkg/runner/check/functions/env_test.go
pkg/runner/check/functions/k8s.go
pkg/runner/check/functions/utils.go

Refactor functions, common utils to get args.

refactor: functions

---

go.mod
pkg/runner/check/functions/functions.go
pkg/runner/check/functions/utils.go
website/docs/jp/functions.md

Add experimental functions prefix.

feat: add experimental functions prefix

---

pkg/runner/operations/apply/apply.go
pkg/runner/operations/apply/apply_test.go
pkg/runner/operations/create/create.go
pkg/runner/operations/create/create_test.go

Fix retry in apply and create operations.

fix: retry in apply and create operations

---

.github/workflows/tests.yaml
pkg/runner/operations/apply/apply.go
testdata/e2e/config.yaml
testdata/e2e/examples/CATALOG.md
testdata/e2e/examples/array-assertion/README.md
testdata/e2e/examples/array-assertion/assertions.yaml
testdata/e2e/examples/array-assertion/chainsaw-test.yaml
testdata/e2e/examples/array-assertion/resources.yaml
website/docs/examples/array-assertions.md
website/mkdocs.yaml

Add array assertions example.
Fixes #695

docs: add array assertions example

---

website/mkdocs.yaml

Fix missing lint command docs.

fix: missing lint command docs

---

.github/workflows/tests.yaml
Makefile

chore: fix create cluster in ci

---

website/docs/community.md

fix: community meeting docs

---

pkg/runner/check/functions/functions.go
pkg/runner/check/functions/functions_test.go
pkg/runner/check/functions/k8s.go
website/docs/jp/functions.md

feat: add kubernetes get func

---

.github/PULL_REQUEST_TEMPLATE.md

added the pr template

---

pkg/runner/check/functions/functions.go
pkg/runner/check/functions/functions_test.go
pkg/runner/check/functions/k8s.go
website/docs/jp/functions.md

add kubernetes exists func

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/feature-request.yaml

added issue template

---

Makefile

Fix : https://github.com/kyverno/chainsaw/issues/737

fix: MakeFile codegen-schemas-json

---

pkg/commands/lint/command.go
pkg/commands/lint/schema.go

Fix schema loader in lint command.
cc @shubham-cmyk

fix: schema loader in lint command

---

.release-notes/main.md
.release-notes/v0.1.2.md

release: v0.1.2

---

pkg/client/client.go
pkg/client/dry_run.go
pkg/client/testing/fake_client.go
pkg/runner/client/client.go

feat: expose rest mapper

---

pkg/runner/processors/step_test.go
pkg/runner/processors/test_test.go
pkg/testing/mock.go
testdata/runner/processors/cron-job.yaml
testdata/runner/processors/deployment.yaml
testdata/runner/processors/pod.yaml

https://github.com/kyverno/chainsaw/issues/556

test: pkg/processor

---

pkg/runner/check/functions/functions.go
pkg/runner/check/functions/functions_test.go
pkg/runner/check/functions/k8s.go
website/docs/jp/functions.md

Added kubernetes resource exists function
Fixes #725

Added kubernetes resource exists function 

---

pkg/commands/migrate/kuttl/config/command.go
pkg/commands/migrate/kuttl/tests/command.go

Add json schema when converting from kuttl.

feat: add json schema when converting from kuttl

---

pkg/commands/migrate/kuttl/tests/command.go
testdata/commands/migrate/kuttl/tests/out.txt
testdata/kuttl/chainsaw-test.yaml

Fix migration of kuttl asserts.

fix: migration of kuttl asserts

---

.github/dependabot.yml

Allow dependabot to rebase PRs.

chore: allow dependabot to rebase PRs

---

.github/workflows/release.yaml
.krew.yaml

Publish chainsaw on krew.
Fixes #163

feat: publish chainsaw on krew

---

.github/workflows/release.yaml

Fix krew release only with stable versions.

fix: krew release only with stable versions

---

README.md
website/docs/community.md

Add chainsaw group in docs and readme.
Fixes #758

chore: add chainsaw group in docs and readme

---

.github/workflows/release.yaml

Remove krew as the plugin was not accepted.

fix: remove krew as the plugin was not accepted

---

.github/workflows/tests.yaml

chore: bump codecov action

---

.github/workflows/tests.yaml

fix: codecov bump

---

.docs/RELEASE.md
.github/ISSUE_TEMPLATE/bug.yaml

Add v0.1.2 in the bug template.

chore: add v0.1.2 in the bug template

---

README.md
website/docs/resources.md

chore: add kubebuilder meeting link

---

CODEOWNERS

chore: test permissions

---

MAINTAINERS.md

chore: add maintainers files

---

MAINTAINERS.md

Add @shubham-cmyk to maintainer list of the kyverno-chainsaw

chore: add @shubham-cmyk  as a maintainer

---

Makefile
testdata/e2e/examples/CATALOG.md
testdata/e2e/examples/command-output/README.md
testdata/kuttl/.chainsaw.yaml

Add makefile target to get the code coverage

chore: add go cover in makefile

---

.release-notes/main.md
Makefile
testdata/e2e/examples/CATALOG.md
testdata/e2e/examples/command-output/README.md
testdata/e2e/examples/command-output/chainsaw-test.yaml

chore: add test catalog codegen

---

.github/workflows/pr-semantics.yaml

chore: add deps PR scope

---

.github/workflows/tests.yaml
Makefile

chore: run e2e tests using makefile

---

website/docs/configuration/values.md
website/docs/operations/check.md
website/mkdocs.yaml

chore: add values docs

---

website/docs/configuration/no-cluster.md
website/mkdocs.yaml

Add docs for running without a kubernetes cluster.

chore: add docs for running without a kubernetes cluster

---

.github/workflows/pr-semantics.yaml

chore: add release semantics

---

.release-notes/main.md
.release-notes/v0.1.3.md

release: v0.1.3

---

.github/ISSUE_TEMPLATE/bug.yaml

chore: add v0.1.3 to drop down list

---

.release-notes/main.md
pkg/commands/test/command.go

Allow passing test dirs by args.

feat: allow passing test dirs by args

---

.crds/chainsaw.kyverno.io_tests.yaml
.crds/chainsaw.kyverno.io_teststeps.yaml
.release-notes/main.md
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/expectation.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
website/docs/apis/chainsaw.v1alpha1.md

Fix an incorrect expectation api docs.

fix: incorrect expectation api docs

---

.crds/chainsaw.kyverno.io_tests.yaml
.crds/chainsaw.kyverno.io_teststeps.yaml
.release-notes/main.md
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/file_ref_or_check.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/runner/processors/step.go
pkg/runner/processors/step_test.go
pkg/validation/file_ref_or_check.go
pkg/validation/file_ref_or_check_test.go
pkg/validation/file_ref_or_resource_test.go
pkg/validation/file_ref_test.go
website/docs/apis/chainsaw.v1alpha1.md

Add missing validation tests and fix api docs.

fix: add missing validation tests and fix api docs

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.yaml
.github/ISSUE_TEMPLATE/general-question.yaml

fix: add missing schemas

---

.crds/chainsaw.kyverno.io_configurations.yaml
.crds/chainsaw.kyverno.io_tests.yaml
.schemas/json/configuration-chainsaw-v1alpha1.json
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/configuration_spec.go
pkg/apis/v1alpha1/test_spec.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/runner/processors/test.go
pkg/runner/processors/tests.go
testdata/e2e/examples/CATALOG.md
testdata/e2e/examples/namespace-modifiers/README.md
testdata/e2e/examples/namespace-modifiers/chainsaw-test.yaml
website/docs/apis/chainsaw.v1alpha1.md

feat: add namespace modifiers

---

.vscode/launch.json

chore: update vscode config

---

pkg/validation/apply.go
pkg/validation/create.go
pkg/validation/modifier.go
pkg/validation/modifiers.go
pkg/validation/test_spec.go

Implement modifier validation.
Fixes #845

feat: implement modifier validation

---

pkg/validation/modifier_test.go
pkg/validation/modifiers_test.go

Add modifier validation unit tests.

chore: add modifier validation tests

---

pkg/runner/mutate/convert.go
pkg/runner/mutate/convert_test.go
pkg/runner/mutate/merge.go
pkg/runner/mutate/merge_test.go

Add modifiers tests.
Fixes #844

chore: add modifiers tests

---

.crds/chainsaw.kyverno.io_configurations.yaml
.crds/chainsaw.kyverno.io_tests.yaml
.schemas/json/configuration-chainsaw-v1alpha1.json
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/configuration_spec.go
pkg/apis/v1alpha1/test_spec.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/runner/operations/apply/apply.go
pkg/runner/operations/create/create.go
pkg/runner/processors/test.go
pkg/runner/processors/tests.go
pkg/validation/test_spec.go
testdata/e2e/examples/CATALOG.md
testdata/e2e/examples/modifiers/chainsaw-test.yaml
testdata/e2e/examples/namespace-template/README.md
testdata/e2e/examples/namespace-template/chainsaw-test.yaml
website/docs/apis/chainsaw.v1alpha1.md

Replace namespace modifiers with namespace template.

feat: replace namespace modifiers with namespace template

---

go.mod
go.sum
pkg/runner/mutate/convert.go
pkg/runner/mutate/convert_test.go
pkg/runner/mutate/merge.go
pkg/runner/operations/apply/apply.go
pkg/runner/operations/create/create.go
testdata/e2e/examples/modifiers/README.md
testdata/e2e/examples/modifiers/chainsaw-test.yaml

feat: add self modifier support

---

.release-notes/main.md
pkg/resource/load.go
testdata/e2e/examples/CATALOG.md
testdata/e2e/examples/list/README.md
testdata/e2e/examples/list/chainsaw-test.yaml
testdata/e2e/examples/list/list.yaml

Fix lists not loaded correctly.
Fixes #858

fix: lists not loaded correctly

---

.release-notes/main.md
pkg/commands/migrate/kuttl/tests/command.go

Improve kuttl tests migration files rewrite logic.

fix: improve kuttl tests migration files rewrite logic

---

go.mod
go.sum
pkg/mutate/expression.go
pkg/mutate/mutate.go
pkg/mutate/mutation.go
pkg/mutate/parse.go
pkg/mutate/project.go
pkg/runner/mutate/merge.go

Add mutation code in chainsaw directly.
This will go back in kyverno-json once the [kdp](https://github.com/kyverno/KDP/pull/57) is accepted.

chore: add mutation code in chainsaw directly

---

.release-notes/main.md
go.mod
pkg/runner/operations/assert/assert.go
pkg/runner/operations/assert/assert_test.go
pkg/runner/operations/errors/resource.go
pkg/utils/diff/diff.go
testdata/e2e/examples/CATALOG.md
testdata/e2e/examples/deployment/README.md
testdata/e2e/examples/deployment/assertions.yaml
testdata/e2e/examples/deployment/chainsaw-test.yaml
testdata/e2e/examples/deployment/resources.yaml

Add diff in assert.
Fixes #775
```shell
| 23:38:59 | deployment | @setup   | CREATE    | OK    | v1/Namespace @ chainsaw-live-newt
| 23:38:59 | deployment | step-1   | TRY       | RUN   |
| 23:38:59 | deployment | step-1   | APPLY     | RUN   | apps/v1/Deployment @ chainsaw-live-newt/example
| 23:38:59 | deployment | step-1   | CREATE    | OK    | apps/v1/Deployment @ chainsaw-live-newt/example
| 23:38:59 | deployment | step-1   | APPLY     | DONE  | apps/v1/Deployment @ chainsaw-live-newt/example
| 23:38:59 | deployment | step-1   | ASSERT    | RUN   | v1/Pod @ chainsaw-live-newt/*
| 23:39:29 | deployment | step-1   | ASSERT    | ERROR | v1/Pod @ chainsaw-live-newt/*
=== ERROR
--------------------------------------------------
v1/Pod/chainsaw-live-newt/example-5477b4ff8c-vpqqn …
```

feat: add diff in assert

---

pkg/runner/operations/assert/assert_test.go
pkg/runner/operations/errors/resource.go

Fix errors in apply not sorted.

fix: errors in apply not sorted

---

.crds/chainsaw.kyverno.io_configurations.yaml
.crds/chainsaw.kyverno.io_tests.yaml
.crds/chainsaw.kyverno.io_teststeps.yaml
.schemas/json/configuration-chainsaw-v1alpha1.json
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/apply.go
pkg/apis/v1alpha1/configuration_spec.go
pkg/apis/v1alpha1/create.go
pkg/apis/v1alpha1/test_spec.go
pkg/apis/v1alpha1/test_step_spec.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/commands/test/command.go
pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/runner/operations/apply/apply.go
pkg/runner/operations/apply/apply_test.go
pkg/runner/operations/create/create.go
pkg/runner/operations/create/create_test.go
pkg/runner/processors/step.go
pkg/runner/template/template.go
pkg/runner/timeout/timeout.go
testdata/commands/test/help.txt
website/docs/apis/chainsaw.v1alpha1.md
website/docs/commands/chainsaw_test.md

feat: add template flag

---

.github/workflows/tests.yaml
Makefile

Improve makefile for ko targets.

chore: improve makefile for ko targets

---

.release-notes/main.md
.release-notes/v0.1.4.md

release: v0.1.4

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/general-question.yaml

chore: update issues drop down

---

.github/workflows/tests.yaml
Makefile

chore: bump tools

---

ADOPTERS.md

No code changes, just adding Grafana-operator as an adopter :)

chore: add grafana-operator to ADOPTERS.md

---

README.md
website/docs/resources.md

Add new blog post in resources.

chore: add new blog post in resources

---

ADOPTERS.md

chore: fix adopters

---

.github/workflows/tests.yaml

Fix unit test coverage upload.

fix: unit test coverage upload

---

pkg/runner/operations/apply/apply.go

Fix invalid json package used.

fix: invalid json package used

---

.crds/chainsaw.kyverno.io_tests.yaml
.crds/chainsaw.kyverno.io_teststeps.yaml
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/configuration_spec.go
pkg/apis/v1alpha1/events.go
pkg/apis/v1alpha1/format.go
pkg/apis/v1alpha1/get.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/runner/kubectl/get.go
pkg/runner/processors/step.go
testdata/e2e/examples/finally/README.md
testdata/e2e/examples/finally/chainsaw-test.yaml
website/docs/apis/chainsaw.v1alpha1.md

Add format support to events and get collectors.
Fixes #902

feat: add format support to events and get collectors

---

.crds/chainsaw.kyverno.io_tests.yaml
.crds/chainsaw.kyverno.io_teststeps.yaml
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/operation.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
website/docs/apis/chainsaw.v1alpha1.md

chore: fix delete operation comment

---

pkg/config/load.go
pkg/config/load_test.go
pkg/validation/config/configuration.go
pkg/validation/config/configuration_spec.go

Add programmatic config validation.

feat: add programmatic config validation

---

.goreleaser.yaml

chore: add image labels

---

.crds/chainsaw.kyverno.io_tests.yaml
.crds/chainsaw.kyverno.io_teststeps.yaml
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/apply.go
pkg/apis/v1alpha1/assert.go
pkg/apis/v1alpha1/command.go
pkg/apis/v1alpha1/create.go
pkg/apis/v1alpha1/delete.go
pkg/apis/v1alpha1/describe.go
pkg/apis/v1alpha1/error.go
pkg/apis/v1alpha1/events.go
pkg/apis/v1alpha1/get.go
pkg/apis/v1alpha1/patch.go
pkg/apis/v1alpha1/pod_logs.go
pkg/apis/v1alpha1/script.go
pkg/apis/v1alpha1/test_spec.go
pkg/apis/v1alpha1/test_step_spec.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
website/docs/apis/chainsaw.v1alpha1.md

Add cluster fields to the api.

feat: add cluster fields to the api

---

pkg/runner/processors/clusters.go
pkg/runner/processors/step.go
pkg/runner/processors/test.go
pkg/runner/processors/tests.go

Use cluster defined in the test/step/operation.

feat: use cluster defined in the test/step/operation

---

.github/workflows/tests.yaml
pkg/runner/processors/clusters.go
pkg/runner/processors/step.go
pkg/runner/processors/test.go
pkg/runner/processors/tests.go
pkg/runner/run.go

fix: `$client` binding

---

pkg/runner/kubectl/describe.go
pkg/runner/kubectl/get.go
pkg/runner/kubectl/pod_logs.go
pkg/runner/processors/step.go

fix: collectors cluster

---

pkg/runner/kubectl/describe.go
pkg/runner/kubectl/describe_test.go
pkg/runner/kubectl/get.go
pkg/runner/kubectl/pod_logs.go

Fixes https://github.com/kyverno/chainsaw/issues/929

fix: timeout in runner/kubectl operations

---

.crds/chainsaw.kyverno.io_configurations.yaml
.release-notes/main.md
.schemas/json/configuration-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/configuration_spec.go
pkg/commands/test/command.go
pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
pkg/report/report.go
pkg/report/report_test.go
pkg/runner/run.go
testdata/commands/test/help.txt
website/docs/apis/chainsaw.v1alpha1.md
website/docs/commands/chainsaw_test.md

Add report-path support.
Fixes #930

feat: add report-path support

---

website/docs/configuration/reports.md

Add docs related to report path.
Related to : https://github.com/kyverno/chainsaw/pull/932

docs(report): add report-path in configuration and flag

---

.crds/chainsaw.kyverno.io_tests.yaml
.crds/chainsaw.kyverno.io_teststeps.yaml
.release-notes/main.md
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/test_step_spec.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/validation/config/cluster.go
pkg/validation/config/configuration_spec.go
pkg/validation/test/test_spec_step.go
pkg/validation/test/test_spec_step_test.go
pkg/validation/test/test_step_spec.go
pkg/validation/test/test_step_spec_test.go

Add more validation.
Fixes #851

feat: add more validation

---

website/docs/steps/catch.md
website/docs/steps/finally.md

Delete in catch/finally blocks.

docs: delete in catch/finally blocks

---

.release-notes/v0.1.6.md
pkg/runner/operations/command/operation.go
pkg/runner/operations/script/operation.go
testdata/e2e/examples/basic/chainsaw-test.yaml

Fix temporary kubeconfig needs to be absolute.

fix: temporary kubeconfig needs to be absolute

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/general-question.yaml

Update drop down in templates.

chore: update drop down in templates

---

pkg/report/report_test.go

test(report): Add report path test

---

pkg/runner/processors/step.go
pkg/runner/processors/test.go

Fix reports creation and potential nil ref panic.

fix: reports creation and potential nil ref panic

---

pkg/report/report.go
pkg/report/report_test.go
pkg/runner/processors/operation.go
pkg/runner/processors/step.go

Fix operation reports missing.

fix: operation reports missing

---

.crds/chainsaw.kyverno.io_tests.yaml
.crds/chainsaw.kyverno.io_teststeps.yaml
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/command.go
pkg/apis/v1alpha1/script.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/runner/processors/step.go
website/docs/apis/chainsaw.v1alpha1.md

Add bindings support in script and command.
Fixes #

feat: add bindings support in script and command

---

pkg/runner/operations/command/operation.go
pkg/runner/operations/script/operation.go

Simplify kubeconfig management.

chore: simplify kubeconfig management

---

pkg/runner/operations/command/operation.go
pkg/runner/operations/script/operation.go

chore: remove path override

---

testdata/e2e/examples/finally/chainsaw-test.yaml

fix: test flake

---

pkg/apis/v1alpha1/wait.go
pkg/runner/kubectl/wait.go
pkg/runner/kubectl/wait_test.go

Fix wait condition value need quotes.

fix: wait condition value need quotes

---

.crds/chainsaw.kyverno.io_tests.yaml
.crds/chainsaw.kyverno.io_teststeps.yaml
.release-notes/main.md
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/operation.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/runner/processors/step.go
pkg/validation/test/catch.go
pkg/validation/test/catch_test.go
pkg/validation/test/finally.go
pkg/validation/test/operation.go
testdata/e2e/examples/CATALOG.md
testdata/e2e/examples/wait/README.md
testdata/e2e/examples/wait/chainsaw-test.yaml
website/docs/apis/chainsaw.v1alpha1.md

feat: add wait operation

---

pkg/runner/kubectl/describe.go
pkg/runner/kubectl/describe_test.go
pkg/runner/kubectl/get.go
pkg/runner/kubectl/get_test.go
pkg/runner/kubectl/logs.go
pkg/runner/kubectl/logs_test.go
pkg/runner/kubectl/wait.go
pkg/runner/kubectl/wait_test.go

fix: do not allow nil collector

---

.release-notes/main.md
.release-notes/v0.1.7.md

release: v0.1.7

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/general-question.yaml

chore: add 0.1.7 to versions list

---

pkg/runner/functions/k8s.go
pkg/runner/functions/k8s_test.go

Fix `jpKubernetesResourceExists` apiVersion handling.

fix: jpKubernetesResourceExists apiVersion handling

---

pkg/runner/processors/step.go

chore: remove unnecessary context

---

pkg/runner/kubectl/describe.go

Detect resource scope in describe.
Fixes #834
Fixes #989

feat: detect resource scope in describe

---

pkg/runner/kubectl/describe.go
pkg/runner/kubectl/describe_test.go
pkg/runner/kubectl/mapping.go
pkg/runner/kubectl/wait.go
pkg/runner/kubectl/wait_test.go
pkg/runner/processors/step.go

Check scope in wait operation.

feat: check scope in wait operation

---

pkg/runner/kubectl/get.go
pkg/runner/kubectl/get_test.go
pkg/runner/kubectl/wait_test.go
pkg/runner/processors/step.go

feat: check scope in get operation

---

pkg/runner/processors/step.go
pkg/runner/processors/test_test.go

fix: operation report name

---

pkg/runner/kubectl/describe.go
pkg/runner/kubectl/get.go
pkg/runner/kubectl/logs.go
pkg/runner/kubectl/wait.go
pkg/runner/kubectl/wait_test.go

feat: support wait --all

---

pkg/runner/kubectl/describe.go
pkg/runner/kubectl/get.go
pkg/runner/kubectl/wait.go

Add `--all-namespaces` support (using `namespace: '*'`).
Fixes #980

feat: add --all-namespaces support

---

pkg/runner/processors/step.go

feat: add rest config binding

---

pkg/runner/functions/functions.go
pkg/runner/functions/functions_test.go
pkg/runner/functions/k8s.go
website/docs/jp/functions.md

Add jp function to fetch server version
Fixes #1016
Fixes #1017

feat: add jp function to fetch server version

---

pkg/runner/functions/k8s.go
testdata/e2e/examples/non-resource-assertion/assert.yaml
testdata/e2e/examples/non-resource-assertion/chainsaw-test.yaml
testdata/e2e/examples/non-resource-assertion/error.yaml

fix: k8s list jp function

---

pkg/runner/processors/operation.go

Improve operation error handling.

fix: improve operation error handling

---

pkg/runner/kubectl/describe.go
pkg/runner/kubectl/describe_test.go
pkg/runner/kubectl/get.go
pkg/runner/kubectl/mapping.go
pkg/runner/kubectl/wait.go

Fix resource short name mapping in collectors.

fix: resource short name mapping in collectors

---

pkg/validation/test/script.go

Fix validate checks in scripts.

fix: validate checks in scripts

---

.release-notes/main.md
.release-notes/v0.1.8.md

release: v0.1.8

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/general-question.yaml

Add v0.1.8 to drop down templates.

chore: add v0.1.8 to drop down templates

---

.release-notes/main.md
pkg/apis/v1alpha1/binding.go
pkg/apis/v1alpha1/binding_test.go

Add unit tests and config as forbidden binding name.

fix: add unit tests and config as forbidden binding name

---

pkg/validation/test/binding_test.go
pkg/validation/test/for_test.go
pkg/validation/test/resource_reference_test.go
pkg/validation/test/test_spec_test.go
pkg/validation/test/test_test.go

chore: add validation unit tests

---

pkg/commands/assert/command_test.go
pkg/testing/err_reader.go
pkg/utils/diff/diff_test.go
pkg/utils/maps/merge_test.go

Add unit tests for the utils package.

chore: add unit tests for the utils package

---

.release-notes/main.md
testdata/e2e/examples/CATALOG.md
testdata/e2e/examples/k8s-server-version/README.md
testdata/e2e/examples/k8s-server-version/chainsaw-test.yaml

Add k8s-server-version example.

chore: add k8s-server-version example

---

.release-notes/main.md
pkg/runner/operations/create/operation.go

Fix create template field management.

fix: create template field management

---

pkg/runner/processors/operation.go
pkg/runner/processors/step.go

Pass bindings and context to collectors.

refactor: pass bindings and context to collectors

---

.release-notes/main.md
pkg/runner/kubectl/describe.go
pkg/runner/kubectl/describe_test.go
pkg/runner/kubectl/get.go
pkg/runner/kubectl/get_test.go
pkg/runner/kubectl/mapping.go
pkg/runner/kubectl/wait.go
pkg/runner/kubectl/wait_test.go
pkg/runner/processors/step.go

Support template in resource reference.
Part of #1035

feat: support template in resource reference

---

.release-notes/main.md
pkg/runner/kubectl/convert.go
pkg/runner/kubectl/describe.go
pkg/runner/kubectl/get.go
pkg/runner/kubectl/logs.go
pkg/runner/kubectl/logs_test.go
pkg/runner/kubectl/mapping.go
pkg/runner/kubectl/wait.go
pkg/runner/processors/step.go

Add more templating support.
Fixes #1035

feat: add more templating support

---

Makefile

chore: fix makefiles dependencies

---

.crds/chainsaw.kyverno.io_configurations.yaml
.crds/chainsaw.kyverno.io_tests.yaml
.crds/chainsaw.kyverno.io_teststeps.yaml
.release-notes/main.md
.schemas/json/configuration-chainsaw-v1alpha1.json
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/format.go
pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
pkg/data/schemas/json/test-chainsaw-v1alpha1.json

fix: format api validation

---

pkg/resource/load_test.go
testdata/resource/list.yaml

Add resource unit tests.
Fixes #1053
Fixes #1055

chore: add resource unit tests

---

.crds/chainsaw.kyverno.io_tests.yaml
.crds/chainsaw.kyverno.io_teststeps.yaml
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/create.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/runner/operations/apply/operation.go
pkg/runner/operations/create/operation.go
pkg/runner/operations/create/operation_test.go
pkg/runner/processors/step.go
website/docs/apis/chainsaw.v1alpha1.md

Add create operation outputs support.

feat: add create operation outputs support

---

.crds/chainsaw.kyverno.io_tests.yaml
.crds/chainsaw.kyverno.io_teststeps.yaml
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/patch.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/runner/operations/apply/operation.go
pkg/runner/operations/assert/operation.go
pkg/runner/operations/command/operation.go
pkg/runner/operations/create/operation.go
pkg/runner/operations/delete/operation.go
pkg/runner/operations/error/operation.go
pkg/runner/operations/patch/operation.go
pkg/runner/operations/patch/operation_test.go
pkg/runner/operations/script/operation.go
pkg/runner/operations/sleep/operation.go
pkg/runner/processors/step.go
website/docs/apis/chainsaw.v1alpha1.md

Add patch operation outputs support.

feat: add patch operation outputs support

---

pkg/runner/kubectl/convert.go
pkg/runner/kubectl/describe.go
pkg/runner/kubectl/get.go
pkg/runner/kubectl/logs.go
pkg/runner/kubectl/mapping.go
pkg/runner/kubectl/wait.go
pkg/runner/operations/apply/operation.go
pkg/runner/processors/cleaner.go
pkg/runner/processors/cleaner_test.go
pkg/runner/processors/info.go
pkg/runner/processors/operation.go
pkg/runner/processors/operation_test.go
pkg/runner/processors/step.go
pkg/runner/processors/step_test.go
pkg/runner/processors/test.go
pkg/runner/processors/test_test.go
pkg/runner/processors/tests.go
pkg/runner/processors/tests_test.go
pkg/runner/run.go
testdata/e2e/examples/CATALOG.md
testdata/e2e/examples/apply-outputs/README.md
testdata/e2e/examples/apply-outputs/chainsaw-test.yaml

Add infos binding.
Fixes #1075

feat: add infos binding

---

.crds/chainsaw.kyverno.io_configurations.yaml
.crds/chainsaw.kyverno.io_tests.yaml
.crds/chainsaw.kyverno.io_teststeps.yaml
.release-notes/main.md
.schemas/json/configuration-chainsaw-v1alpha1.json
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/binding.go
pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
pkg/data/schemas/json/test-chainsaw-v1alpha1.json

fix: add binding name validation

---

.crds/chainsaw.kyverno.io_configurations.yaml
.crds/chainsaw.kyverno.io_tests.yaml
.crds/chainsaw.kyverno.io_teststeps.yaml
.release-notes/main.md
.schemas/json/configuration-chainsaw-v1alpha1.json
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/command.go
pkg/apis/v1alpha1/script.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/runner/operations/apply/operation.go
pkg/runner/operations/command/operation.go
pkg/runner/operations/create/operation.go
pkg/runner/operations/patch/operation.go
pkg/runner/operations/script/operation.go
pkg/validation/test/command.go
pkg/validation/test/output.go
pkg/validation/test/script.go
website/docs/apis/chainsaw.v1alpha1.md

Add match support in script and command outputs.

feat: add match support in script and command outputs

---

.release-notes/main.md
pkg/runner/operations/internal/env.go

Add env name template support in command and script.

feat: add env name template support in command and script

---

.crds/chainsaw.kyverno.io_configurations.yaml
.crds/chainsaw.kyverno.io_tests.yaml
.crds/chainsaw.kyverno.io_teststeps.yaml
.release-notes/main.md
.schemas/json/configuration-chainsaw-v1alpha1.json
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/binding.go
pkg/apis/v1alpha1/binding_test.go
pkg/apis/v1alpha1/format.go
pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/runner/bindings/bindings.go
pkg/runner/operations/internal/env.go
testdata/e2e/examples/apply-outputs/chainsaw-test.yaml

Refactor binding names validation.

refactor: binding names validation

---

pkg/runner/bindings/bindings.go
pkg/runner/bindings/outputs.go
pkg/runner/bindings/string.go
pkg/runner/kubectl/describe.go
pkg/runner/kubectl/get.go
pkg/runner/kubectl/logs.go
pkg/runner/kubectl/mapping.go
pkg/runner/kubectl/wait.go
pkg/runner/operations/apply/operation.go
pkg/runner/operations/command/operation.go
pkg/runner/operations/create/operation.go
pkg/runner/operations/patch/operation.go
pkg/runner/operations/script/operation.go

refactor: output bindings

---

.release-notes/main.md
pkg/commands/build/docs/command.go
pkg/commands/build/docs/docs.tmpl
testdata/e2e/examples/apply-outputs/README.md
testdata/e2e/examples/array-assertion/README.md
testdata/e2e/examples/assertion-tree/README.md
testdata/e2e/examples/basic/README.md
testdata/e2e/examples/bindings/README.md
testdata/e2e/examples/catch/README.md
testdata/e2e/examples/command-output/README.md
testdata/e2e/examples/delete/README.md
testdata/e2e/examples/deployment/README.md
testdata/e2e/examples/finally/README.md
testdata/e2e/examples/inline/README.md
testdata/e2e/examples/k8s-server-version/README.md
testdata/e2e/examples/list/README.md
testdata/e2e/examples/namespace-template/README.md
testdata/e2e/examples/non-resource-assertion/README.md
testdata/e2e/examples/outputs/README.md
testdata/e2e/examples/patch/README.md
testdata/e2e/examples/script-env/README.md
testdata/e2e/examples/sleep/README.md
testdata/e2e/examples/template/README.md
testdata/e2e/examples/timeout/README.md
testdata/e2e/examples/values/README.md
testdata/e2e/examples/wait/README.md

Fix build docs command for files with multiple tests.

fix: build docs command for files with multiple tests

---

pkg/apis/v1alpha1/catch.go
pkg/apis/v1alpha1/finally.go
pkg/apis/v1alpha1/operation.go
pkg/commands/build/docs/docs.tmpl
testdata/e2e/examples/apply-outputs/README.md
testdata/e2e/examples/array-assertion/README.md
testdata/e2e/examples/assertion-tree/README.md
testdata/e2e/examples/basic/README.md
testdata/e2e/examples/bindings/README.md
testdata/e2e/examples/catch/README.md
testdata/e2e/examples/command-output/README.md
testdata/e2e/examples/delete/README.md
testdata/e2e/examples/deployment/README.md
testdata/e2e/examples/finally/README.md
testdata/e2e/examples/inline/README.md
testdata/e2e/examples/k8s-server-version/README.md
testdata/e2e/examples/list/README.md
testdata/e2e/examples/namespace-template/README.md
testdata/e2e/examples/non-resource-assertion/README.md
testdata/e2e/examples/outputs/README.md
testdata/e2e/examples/patch/README.md
testdata/e2e/examples/script-env/README.md
testdata/e2e/examples/sleep/README.md
testdata/e2e/examples/template/README.md
testdata/e2e/examples/timeout/README.md
testdata/e2e/examples/update/README.md
testdata/e2e/examples/values/README.md
testdata/e2e/examples/wait/README.md

Add bindings in build docs command.
Fixes #1069

feat: add bindings in build docs command

---

.release-notes/main.md
pkg/runner/operations/assert/operation.go
pkg/runner/operations/errors/resource.go

Fix template in assert diff.
Fixes #1094

fix: template in assert diff

---

pkg/apis/v1alpha1/catch_test.go
pkg/apis/v1alpha1/finally_test.go
pkg/apis/v1alpha1/operation_test.go

chore: add api unit tests

---

pkg/client/dry_run_test.go

chore: add client unit tests

---

pkg/mutate/expression.go
pkg/mutate/parse.go

chore: clean mutate package

---

.release-notes/main.md
.release-notes/v0.1.9.md

release: v0.1.9

---

website/docs/install.md

Added instructions to install `kyverno-chainsaw`
Fixes #1121

docs: Updated installation doc for nix package manager

---

.release-notes/main.md
pkg/runner/kubectl/wait.go
pkg/runner/kubectl/wait_test.go

fix: wait timeout

---

.release-notes/main.md
pkg/commands/export/schemas/command.go
pkg/commands/lint/schema.go
pkg/commands/test/command.go

Fix issue reading files from embedded file systems on windows.
Fixes #1140

fix: issue reading files from embedded file systems on windows

---

README.md
website/docs/resources.md

Update resources with Viktor video

chore: update resources with Viktor video

---

ADOPTERS.md

Add Provider Ceph to Adopters list.
https://github.com/linode/provider-ceph/pull/221

chore: Add Provider Ceph to ADOPTERS.md

---

ADOPTERS.md

Add Linode CAPI provider to Adopters list.
https://github.com/linode/cluster-api-provider-linode/pull/181

chore: Add Linode CAPI to ADOPTERS.md

---

.crds/chainsaw.kyverno.io_configurations.yaml
.release-notes/main.md
.schemas/json/configuration-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/cluster.go
pkg/apis/v1alpha1/configuration_spec.go
pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
website/docs/apis/chainsaw.v1alpha1.md

fix: add missing cluster docs

---

pkg/runner/kubectl/wait.go
pkg/runner/kubectl/wait_test.go

Fix shell expansion in wait with json path condition.
Fixes #1146

fix: shell expansion in wait with json path condition

---

.release-notes/main.md
pkg/runner/operations/update/operation.go
testdata/e2e/examples/CATALOG.md
testdata/e2e/examples/update-crd/README.md
testdata/e2e/examples/update-crd/chainsaw-test.yaml
testdata/e2e/examples/update-crd/crd.yaml

Fix resource version when updating.
Fixes #1158

fix: set resource version when updating

---

Makefile
pkg/config/load.go
pkg/config/load_test.go
testdata/e2e/config-v1alpha2.yaml

Use v1alpha2 config in e2e tests.

chore: use v1alpha2 config in e2e tests

---

.github/workflows/check-actions.yaml
.github/workflows/check-milestone.yaml
.github/workflows/codegen.yaml
.github/workflows/codeql.yaml
.github/workflows/docs-release.yaml
.github/workflows/lint.yaml
.github/workflows/pr-semantics.yaml
.github/workflows/release.yaml
.github/workflows/tests.yaml

Update jobs to work on release branches.

chore: update jobs to work on release branches

---

.github/workflows/pr-semantics.yaml

Disable semantics pr check for cherry pick bot.

chore: disable semantics pr check for cherry pick bot

---

.github/workflows/check-actions.yaml
.github/workflows/codegen.yaml
.github/workflows/codeql.yaml
.github/workflows/docs-main.yaml
.github/workflows/docs-release.yaml
.github/workflows/lint.yaml
.github/workflows/pr-semantics.yaml
.github/workflows/tests.yaml

chore: fix ci jobs

---

ADOPTERS.md

Add Linode COSI to Adopters list.
https://github.com/linode/linode-cosi-driver/pull/55

docs: add Linode COSI to ADOPTERS.md

---

.github/workflows/pr-semantics.yaml

missing cherry-picks from main

cherry-pick: release 0.2

---

go.mod
go.sum

Use upstream kubectl-validate.

chore: use upstream kubectl-validate

---

.release-notes/main.md
.release-notes/v0.2.0.md

release: v0.2.0

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/general-question.yaml

chore: update issue templates

---

.release-notes/main.md
pkg/runner/template/template.go
testdata/commands/test/help.txt
website/docs/commands/chainsaw_test.md

feat: enable templating by default

---

.release-notes/main.md
pkg/runner/operations/delete/operation.go
testdata/e2e/examples/CATALOG.md
testdata/e2e/examples/orphan/README.md
testdata/e2e/examples/orphan/chainsaw-test.yaml

Force background propagation deletion.

feat: force background propagation deletion

---

pkg/runner/clusters/cluster.go

Make sure we resolve cluster only once.

fix: make sure we resolve cluster only once

---

.release-notes/main.md
.release-notes/v0.2.1.md

release: v0.2.1

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/general-question.yaml

Add v0.2.1 in bug reports template.

chore: add v0.2.1 in bug reports template

---

.release-notes/main.md
website/docs/index.md
website/docs/static/repo-card.js
website/mkdocs.base.yaml

fix: disable instant nav

---

website/docs/overrides/home.html

fix: improve home page

---

website/mkdocs.yaml

Move community page to its own tab.

chore: move community page to its own tab

---

website/docs/docs.md
website/docs/install.md
website/docs/intro.md
website/mkdocs.yaml

chore: improve install page

---

website/docs/completion.md
website/docs/first-test.md
website/docs/intro.md
website/docs/run-test.md
website/mkdocs.yaml

chore: rework introduction

---

website/docs/intro.md
website/docs/operation-outputs.md
website/docs/resource-templating.md
website/docs/run-test.md
website/mkdocs.yaml

chore: add resource templating into

---

website/docs/configuration/timeouts.md
website/docs/quick-start/first-test.md
website/docs/quick-start/index.md
website/docs/quick-start/install.md
website/docs/quick-start/resource-templating.md
website/docs/quick-start/run-tests.md
website/docs/quick-start/timeouts.md
website/docs/quick-start/try-catch.md

chore: improve timeouts quick start

---

website/docs/quick-start/assertion-trees.md
website/docs/quick-start/bindings.md
website/docs/quick-start/install.md
website/docs/quick-start/resource-templating.md
website/docs/quick-start/run-tests.md
website/docs/quick-start/timeouts.md

chore: improve bindings page

---

website/docs/quick-start/try-catch.md

Improve try catch finally page.

chore: improve try catch finally page

---

website/docs/quick-start/bindings.md
website/docs/quick-start/resource-templating.md
website/docs/quick-start/try-catch.md

Improve resource templating docs.

docs: resource templating docs

---

website/docs/quick-start/operation-outputs.md

Improve operation outputs page.

docs: operation outputs page

---

pkg/runner/processors/step.go
pkg/runner/processors/step_test.go
testdata/e2e/examples/dynamic-clusters/chainsaw-test.yaml

Fix catch/finally execution order.
Fixes #1340

fix: catch/finally execution order

---

website/docs/quick-start/advanced/cluster-wide-resources.md
website/docs/quick-start/advanced/concurrency.md
website/docs/quick-start/advanced/crds.md
website/docs/quick-start/advanced/kube-version.md
website/docs/quick-start/advanced/multi-cluster.md
website/docs/quick-start/advanced/negative-testing.md
website/docs/quick-start/advanced/non-resource-assertions.md
website/mkdocs.yaml

Add placeholder for advanced use cases docs.

docs: add placeholder for advanced use cases

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/general-question.yaml
.release-notes/main.md
.release-notes/v0.2.2.md

release: v0.2.2

---

.release-notes/main.md
pkg/validation/test/test_step_spec.go

Add cleanup validation logic.
Fixes #1365

feat: add cleanup validation logic

---

pkg/commands/build/docs/docs.tmpl
testdata/e2e/examples/apply-outputs/README.md
testdata/e2e/examples/array-assertion/README.md
testdata/e2e/examples/assertion-tree/README.md
testdata/e2e/examples/basic/README.md
testdata/e2e/examples/bindings/README.md
testdata/e2e/examples/catch/README.md
testdata/e2e/examples/command-output/README.md
testdata/e2e/examples/delete/README.md
testdata/e2e/examples/deployment/README.md
testdata/e2e/examples/dynamic-clusters/README.md
testdata/e2e/examples/finally/README.md
testdata/e2e/examples/inline/README.md
testdata/e2e/examples/k8s-server-version/README.md
testdata/e2e/examples/list/README.md
testdata/e2e/examples/namespace-template-config/README.md
testdata/e2e/examples/namespace-template/README.md
testdata/e2e/examples/non-resource-assertion/README.md
testdata/e2e/examples/orphan/README.md
testdata/e2e/examples/outputs/README.md
testdata/e2e/examples/patch/README.md
testdata/e2e/examples/quick-start/README.md
testdata/e2e/examples/script-env/README.md
testdata/e2e/examples/sleep/README.md
testdata/e2e/examples/template/README.md
testdata/e2e/examples/timeout/README.md
testdata/e2e/examples/update-crd/README.md
testdata/e2e/examples/update/README.md
testdata/e2e/examples/values/README.md
testdata/e2e/examples/wait/README.md

Add cleanup support to tests catalog.
Fixes #1366

feat: add cleanup support to tests catalog

---

website/docs/quick-start/advanced/concurrency.md
website/docs/quick-start/advanced/kube-version.md
website/mkdocs.yaml

Advanced check kube version docs.

docs: advanced check kube version docs

---

testdata/e2e/examples/CATALOG.md
testdata/e2e/examples/negative-testing/resource/README.md
testdata/e2e/examples/negative-testing/resource/chainsaw-test.yaml
testdata/e2e/examples/negative-testing/resource/resources.yaml
testdata/e2e/examples/negative-testing/script/README.md
testdata/e2e/examples/negative-testing/script/chainsaw-test.yaml
website/docs/quick-start/advanced/negative-testing.md

docs: negative testing guide

---

website/docs/quick-start/advanced/cluster-wide-resources.md
website/docs/quick-start/assertion-trees.md
website/docs/quick-start/first-test.md
website/mkdocs.base.yaml
website/mkdocs.yaml

Improve assertion guide.
Fixes #1381

docs: improve assertion guide

---

.crds/chainsaw.kyverno.io_configurations.yaml
.schemas/json/configuration-chainsaw-v1alpha2.json
pkg/apis/v1alpha2/configuration.go
pkg/apis/v1alpha2/types.go
pkg/apis/v1alpha2/types_conversion.go
pkg/apis/v1alpha2/zz_generated.deepcopy.go
pkg/data/config/default.yaml
pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
pkg/data/schemas/json/configuration-chainsaw-v1alpha2.json
testdata/commands/test/default.txt
testdata/commands/test/with_regex.txt
testdata/commands/test/with_repeat_count.txt
testdata/commands/test/with_suppress.txt
testdata/commands/test/with_test_dirs.txt
testdata/commands/test/with_timeout.txt
website/docs/apis/chainsaw.v1alpha2.md

Update default config to v1alpha2.

feat: update default config to v1alpha2

---

website/docs/overrides/home.html

Add arrows to navigate home sections.

feat: add arrows to navigate home sections

---

pkg/apis/v1alpha2/types.go
testdata/e2e/config.yaml
website/docs/apis/chainsaw.v1alpha2.md
website/docs/configuration/index.md
website/docs/configuration/options/deletion.md
website/docs/json-schemas.md
website/mkdocs.yaml

Update default config to v1alpha2 (part 3).

feat: update default config to v1alpha2 (part 3)

---

website/docs/json-schemas.md
website/docs/quick-start/next-steps.md
website/docs/reference/index.md
website/mkdocs.yaml

chore: reference docs nits

---

.gitignore
Makefile
website/mkdocs.base.yaml

chore: enable social cards

---

ADOPTERS.md

Adds OpenFeature to the list of adopters

chore: add OpenFeature to list of adopters

---

pkg/runner/failer/failer.go

fix: linter error

---

website/docs/operations/apply.md
website/docs/operations/assert.md
website/docs/operations/command.md
website/docs/operations/create.md
website/docs/operations/delete.md
website/docs/operations/error.md
website/docs/operations/helpers/logs.md
website/docs/operations/helpers/wait.md
website/docs/operations/index.md
website/docs/operations/patch.md
website/docs/operations/script.md
website/docs/operations/sleep.md
website/docs/operations/update.md
website/mkdocs.yaml

docs: restructure test docs

---

website/docs/overrides/home.html

Add positive/negative testing to home.

chore: add positive/negative testing to home

---

.release-notes/main.md

chore: update v0.2.3 release notes

---

.release-notes/main.md
pkg/runner/processors/info.go
pkg/runner/processors/tests.go
testdata/e2e/examples/CATALOG.md
testdata/e2e/examples/test-info/README.md
testdata/e2e/examples/test-info/chainsaw-test.yaml
website/docs/reference/builtins.md

Add test metadata binding.
Fixes #1471

feat: add test metadata binding

---

.crds/chainsaw.kyverno.io_configurations.yaml
.crds/chainsaw.kyverno.io_tests.yaml
.schemas/json/configuration-chainsaw-v1alpha1.json
.schemas/json/configuration-chainsaw-v1alpha2.json
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/delete.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/commands/create/test/command.go
pkg/commands/migrate/kuttl/tests/command.go
pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
pkg/data/schemas/json/configuration-chainsaw-v1alpha2.json
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/runner/processors/step.go
pkg/runner/processors/step_test.go
pkg/validation/test/catch_test.go
pkg/validation/test/delete.go
pkg/validation/test/finally_test.go
pkg/validation/test/operation_test.go
website/docs/reference/apis/chainsaw.v1alpha1.md

Refactor delete operation reference.

refactor: delete operation reference

---

.crds/chainsaw.kyverno.io_configurations.yaml
.crds/chainsaw.kyverno.io_tests.yaml
.release-notes/main.md
.schemas/json/configuration-chainsaw-v1alpha1.json
.schemas/json/configuration-chainsaw-v1alpha2.json
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/delete.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/commands/create/test/command.go
pkg/commands/migrate/kuttl/tests/command.go
pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
pkg/data/schemas/json/configuration-chainsaw-v1alpha2.json
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/runner/processors/step.go
pkg/runner/processors/step_test.go
pkg/validation/test/catch_test.go
pkg/validation/test/delete.go
pkg/validation/test/finally_test.go
pkg/validation/test/operation_test.go
testdata/e2e/examples/CATALOG.md
testdata/e2e/examples/delete/README.md
testdata/e2e/examples/delete/chainsaw-test.yaml
testdata/e2e/examples/delete/cms.yaml
website/docs/reference/apis/chainsaw.v1alpha1.md

Add file support to delete operation.

feat: add file support to delete operation

---

pkg/validation/test/operation.go

Fix patch validation incorrect field.

fix: patch validation incorrect field

---

.crds/chainsaw.kyverno.io_tests.yaml
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/operation.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/runner/processors/step.go
pkg/validation/test/operation.go
website/docs/reference/apis/chainsaw.v1alpha1.md

feat: add missing operations

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/general-question.yaml
.release-notes/main.md
.release-notes/v0.2.4.md

release: v0.2.4

---

.release-notes/v0.2.4.md

chore: fix release notes

---

.crds/chainsaw.kyverno.io_configurations.yaml
.release-notes/main.md
pkg/apis/v1alpha2/configuration.go
pkg/apis/v1alpha2/options.go
pkg/data/crds/chainsaw.kyverno.io_configurations.yaml

fix: default values in api

---

.gitignore
Makefile
requirements.txt

fix: use python virtual env

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/general-question.yaml
.release-notes/main.md
.release-notes/v0.2.5.md

release: v0.2.5

---

pkg/metrics/decode.go
pkg/runner/functions/functions.go
pkg/runner/functions/functions_test.go
pkg/runner/functions/metrics.go
testdata/e2e/examples/CATALOG.md
testdata/e2e/examples/metrics-decode/README.md
testdata/e2e/examples/metrics-decode/chainsaw-test.yaml
website/docs/reference/jp/functions.md

Add jp function to decode metrics.

feat: add jp function to decode metrics

---

.github/workflows/pr-semantics.yaml

chore(deps): bump amannn/action-semantic-pull-request (cherry-pick #1592)

chore(deps): bump amannn/action-semantic-pull-request (cherry-pick #1592)

---

pkg/commands/build/docs/catalog.tmpl
pkg/commands/build/docs/docs.tmpl
pkg/commands/test/command.go
pkg/discovery/discovery.go
pkg/discovery/test.go
pkg/report/junit.go
pkg/runner/names/test.go
pkg/runner/processors/step.go
pkg/runner/processors/test.go
pkg/runner/processors/tests.go

chore: use a named field for test

---

.crds/chainsaw.kyverno.io_tests.yaml
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/action.go
pkg/apis/v1alpha1/operation.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/schemas/json/test-chainsaw-v1alpha1.json

feat: model schema based validation

---

.crds/chainsaw.kyverno.io_configurations.yaml
.crds/chainsaw.kyverno.io_tests.yaml
.schemas/json/configuration-chainsaw-v1alpha1.json
.schemas/json/configuration-chainsaw-v1alpha2.json
.schemas/json/test-chainsaw-v1alpha1.json
.schemas/json/test-chainsaw-v1alpha2.json
hack/controller-gen/main.go
hack/controller-gen/markers.go
pkg/apis/v1alpha1/action.go
pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
pkg/data/schemas/json/configuration-chainsaw-v1alpha2.json
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/data/schemas/json/test-chainsaw-v1alpha2.json

feat: more schema based valdation

---

.crds/chainsaw.kyverno.io_configurations.yaml
.crds/chainsaw.kyverno.io_tests.yaml
.schemas/json/configuration-chainsaw-v1alpha1.json
.schemas/json/configuration-chainsaw-v1alpha2.json
.schemas/json/test-chainsaw-v1alpha1.json
.schemas/json/test-chainsaw-v1alpha2.json
hack/controller-gen/main.go
hack/controller-gen/markers.go
pkg/apis/v1alpha1/action.go
pkg/apis/v1alpha1/catch_finally.go
pkg/apis/v1alpha1/operation.go
pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
pkg/data/schemas/json/configuration-chainsaw-v1alpha2.json
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/data/schemas/json/test-chainsaw-v1alpha2.json

feat: more model based validation

---

pkg/discovery/discovery_test.go
pkg/discovery/load_test.go
pkg/discovery/test.go
pkg/model/model.go
pkg/runner/flags/flags.go
pkg/runner/flags/flags_test.go
pkg/runner/internal/flags.go
pkg/runner/names/test.go
pkg/runner/names/test_test.go
pkg/runner/processors/step.go
pkg/runner/processors/step_test.go
pkg/runner/processors/test.go
pkg/runner/processors/test_test.go
pkg/runner/processors/tests.go
pkg/runner/processors/tests_test.go
pkg/runner/run.go
pkg/runner/run_test.go

feat: introduce model package

---

.crds/chainsaw.kyverno.io_tests.yaml
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/step.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/discovery/load.go
testdata/e2e/examples/step-template/chainsaw-test.yaml
website/docs/reference/apis/chainsaw.v1alpha1.md

chore: rename from to use

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/general-question.yaml
.release-notes/main.md
.release-notes/v0.2.7.md

release: v0.2.7

---

pkg/runner/processors/tests.go

chore: remove unused code

---

pkg/runner/processors/test.go
pkg/runner/processors/test_test.go
pkg/runner/processors/tests.go

Reduce coupling to test framework.

refactor: reduce coupling to test framework

---

pkg/runner/names/test.go
pkg/runner/names/test_test.go
pkg/runner/processors/tests.go

refactor: names package

---

pkg/model/context.go
pkg/runner/processors/mocks.go
pkg/runner/processors/test.go
pkg/runner/processors/test_test.go
pkg/runner/processors/tests.go
pkg/runner/processors/tests_test.go

refactor: more test context

---

pkg/model/context.go
pkg/runner/processors/test.go
pkg/runner/processors/test_test.go
pkg/runner/processors/tests.go
pkg/runner/processors/tests_test.go
pkg/runner/run.go

refactor: simplify test context

---

pkg/commands/renovate/config/command.go
pkg/commands/test/command.go
pkg/data/data.go
pkg/data/data_test.go

refactor: data package

---

pkg/model/context.go
pkg/model/evaluate.go
pkg/runner/processors/step.go
pkg/runner/processors/step_test.go
pkg/runner/processors/test.go
pkg/runner/processors/tests.go
pkg/runner/run.go
pkg/runner/run_test.go

refactor: timeouts management

---

pkg/runner/processors/tests.go

Refactor fail fast management.

refactor: fail fast management

---

pkg/runner/processors/context.go
pkg/runner/processors/step.go

refactor: test context setup

---

.release-notes/main.md
pkg/runner/processors/operation.go
pkg/runner/processors/test.go

Fix operation info not registered before other bindings.

fix: operation info not registered before other bindings

---

pkg/model/context.go
pkg/runner/processors/context.go
pkg/runner/processors/step.go

refactor: dry run management

---

.release-notes/main.md
pkg/runner/processors/step.go

Delay operation loading until execution.

feat: delay operation loading until execution

---

codecov.yml

chore: improve codecov config

---

pkg/cleanup/cleaner/cleaner.go
pkg/cleanup/cleaner/cleaner_test.go
pkg/runner/processors/step.go

chore: add cleaner unit tests

---

.crds/chainsaw.kyverno.io_tests.yaml
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/test.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/engine/context.go
pkg/runner/processors/context.go
pkg/runner/processors/namespace.go
pkg/runner/processors/scenarios.go
pkg/runner/processors/step.go
pkg/runner/processors/test.go
pkg/runner/processors/test_test.go
pkg/runner/processors/tests.go
pkg/runner/run.go
website/docs/reference/apis/chainsaw.v1alpha1.md

refactor: test context

---

pkg/cleanup/cleaner/cleaner.go
pkg/cleanup/cleaner/cleaner_test.go
pkg/runner/processors/step.go
pkg/runner/processors/test.go
pkg/runner/processors/tests.go

fix: propagation policy

---

.schemas/json/steptemplate-chainsaw-v1alpha1.json
.schemas/json/test-chainsaw-v1alpha1.json
.schemas/json/test-chainsaw-v1alpha2.json
pkg/data/schemas/json/steptemplate-chainsaw-v1alpha1.json
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/data/schemas/json/test-chainsaw-v1alpha2.json

Fix openapi2jsonschema strict mode.

fix: openapi2jsonschema strict mode

---

pkg/apis/v1alpha1/action.go
pkg/apis/v1alpha1/types.go
pkg/commands/migrate/kuttl/tests/command.go
pkg/discovery/load.go
pkg/runner/processors/step.go
website/docs/reference/apis/chainsaw.v1alpha1.md

Add type for string expressions.

feat: add type for string expressions

---

pkg/apis/v1alpha1/action.go
pkg/apis/v1alpha1/types.go
pkg/apis/v1alpha1/types_test.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/commands/migrate/kuttl/tests/command.go
pkg/engine/bindings/bindings.go
pkg/engine/kubectl/describe.go
pkg/engine/kubectl/get.go
pkg/engine/kubectl/logs.go
pkg/engine/kubectl/mapping.go
pkg/engine/kubectl/proxy.go
pkg/engine/kubectl/wait.go
pkg/engine/kubectl/wait_test.go
pkg/runner/processors/step.go
website/docs/reference/apis/chainsaw.v1alpha1.md

feat: migrate to new expressions

---

pkg/apis/v1alpha1/types.go

Compile expressions when unmarshaling.

feat: compile expressions when unmarshaling

---

pkg/engine/client/client.go
pkg/engine/logging/logger.go
pkg/engine/operations/command/operation.go
pkg/engine/operations/script/operation.go
pkg/runner/processors/step.go
pkg/runner/processors/test.go
pkg/runner/processors/tests.go

Add begin, end, and warning log statuses.

feat: add begin, end, and warning log statuses

---

pkg/client/simple/client.go
testdata/e2e/examples/CATALOG.md
testdata/e2e/examples/field-validation/README.md
testdata/e2e/examples/field-validation/chainsaw-test.yaml
testdata/e2e/examples/quick-start/chainsaw-test.yaml

Add server side validation support.

feat: add server side validation support

---

.goreleaser.yaml

feat: add ppc64le and s390x builds

---

pkg/engine/operations/command/operation.go
pkg/engine/operations/command/operation_test.go
pkg/engine/operations/script/operation.go
pkg/engine/operations/script/operation_test.go

feat: work dir override follow-up

---

pkg/commands/lint/command.go
pkg/commands/lint/schema.go

Fix lint different versions.
Fixes #1884

fix: lint different versions

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/general-question.yaml
.goreleaser.yaml
.release-notes/main.md
.release-notes/v0.2.9.md

release: v0.2.9

---

.github/workflows/check-actions.yaml
.release-notes/main.md
pkg/commands/test/command.go

Fix default report name not set correctly.
Fixes #1938

fix: default report name not set correctly

---

go.mod
go.sum
pkg/report/junit.go

feat: use jstemmer/go-junit-report

---

pkg/model/report.go
pkg/report/junit.go
pkg/runner/processors/step.go
pkg/runner/processors/step_test.go
pkg/runner/processors/test.go

feat: restructure junit reports

---

pkg/model/report.go
pkg/runner/processors/operation.go
pkg/runner/processors/operation_test.go
pkg/runner/processors/step.go

refactor: report system

---

pkg/runner/processors/operation.go
pkg/runner/processors/operation_test.go
pkg/runner/processors/step.go

Decouple operation execution from failer.

refactor: decouple operation execution from failer

---

pkg/model/report.go
pkg/report/junit.go
pkg/runner/processors/operation.go
pkg/runner/processors/step.go

Refactor failure propagation in reports.

refactor: failure propagation in reports

---

pkg/report/json.go

feat: improve json report format

---

pkg/model/report.go
pkg/report/junit.go
pkg/runner/processors/operation.go
pkg/runner/processors/step.go
pkg/runner/processors/test.go

Add cleanup operations in reports.

feat: add cleanup operations in reports

---

pkg/model/report.go
pkg/report/json.go
pkg/report/junit.go

Refactor reports failures propagation.

refactor: reports failures propagation

---

pkg/runner/processors/step.go

Move cleanup in separate report steps.

feat: move cleanup in separate report steps

---

pkg/cleanup/cleaner/cleaner.go
pkg/cleanup/cleaner/cleaner_test.go
pkg/runner/processors/step.go
pkg/runner/processors/test.go
pkg/runner/processors/tests.go

feat: add test cleanup to report

---

.crds/chainsaw.kyverno.io_configurations.yaml
.schemas/json/configuration-chainsaw-v1alpha1.json
.schemas/json/configuration-chainsaw-v1alpha2.json
pkg/apis/v1alpha1/configuration.go
pkg/apis/v1alpha2/options.go
pkg/commands/test/command.go
pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
pkg/data/schemas/json/configuration-chainsaw-v1alpha2.json
pkg/report/junit.go
pkg/report/report.go
testdata/commands/test/help.txt
website/docs/reference/apis/chainsaw.v1alpha1.md
website/docs/reference/apis/chainsaw.v1alpha2.md
website/docs/reference/commands/chainsaw_test.md

Refactor junit report structure.
Added new formats:
- JUNIT-TEST
- JUNIT-STEP
- JUNIT-OPERATION
Fixes https://github.com/kyverno/chainsaw/issues/1537

refactor: junit report structure

---

.crds/chainsaw.kyverno.io_tests.yaml
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/step.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/discovery/load.go

Make `template` required in step template.

fix: make template required in step template

---

.github/dependabot.yml

Fix dependabot gomod directories.

fix: dependabot gomod directories

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/general-question.yaml
.release-notes/main.md
.release-notes/v0.2.10.md

release: v0.2.10

---

pkg/runner/processors/tests.go

Fix exit code when failing in root test run.

fix: exit code when failing in root test run

---

.schemas/json/configuration-chainsaw-v1alpha1.json
.schemas/json/configuration-chainsaw-v1alpha2.json
.schemas/json/steptemplate-chainsaw-v1alpha1.json
.schemas/json/test-chainsaw-v1alpha1.json
Makefile
pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
pkg/data/schemas/json/configuration-chainsaw-v1alpha2.json
pkg/data/schemas/json/steptemplate-chainsaw-v1alpha1.json
pkg/data/schemas/json/test-chainsaw-v1alpha1.json

chore: update kind to 1.31

---

go.mod
go.sum
website/docs/reference/jp/examples/at.md
website/docs/reference/jp/examples/concat.md
website/docs/reference/jp/examples/json_parse.md
website/docs/reference/jp/examples/wildcard.md
website/docs/reference/jp/functions.md

feat: bump kyverno-json

---

.crds/chainsaw.kyverno.io_tests.yaml
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/test.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/runner/processors/test.go
website/docs/reference/apis/chainsaw.v1alpha1.md

Add default compiler at the test api level.

feat: add default compiler at the test api level

---

.crds/chainsaw.kyverno.io_tests.yaml
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/step.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/runner/processors/step.go
website/docs/reference/apis/chainsaw.v1alpha1.md

Add compiler at the step api level.

feat: add compiler at the step api level

---

testdata/e2e/config.yaml
testdata/e2e/examples/CATALOG.md
testdata/e2e/examples/cel/README.md
testdata/e2e/examples/cel/chainsaw-test.yaml

feat: add cel test

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/general-question.yaml
.release-notes/_template.md
.release-notes/v0.2.11.md

release: v0.2.11

---

Makefile

chore: fix typo in makefile

---

testdata/e2e/examples/CATALOG.md

fix: update codegen

---

.crds/chainsaw.kyverno.io_configurations.yaml
.crds/chainsaw.kyverno.io_steptemplates.yaml
.crds/chainsaw.kyverno.io_tests.yaml
.schemas/json/configuration-chainsaw-v1alpha1.json
.schemas/json/configuration-chainsaw-v1alpha2.json
.schemas/json/steptemplate-chainsaw-v1alpha1.json
.schemas/json/test-chainsaw-v1alpha1.json
pkg/apis/v1alpha1/action.go
pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
pkg/data/crds/chainsaw.kyverno.io_steptemplates.yaml
pkg/data/crds/chainsaw.kyverno.io_tests.yaml
pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
pkg/data/schemas/json/configuration-chainsaw-v1alpha2.json
pkg/data/schemas/json/steptemplate-chainsaw-v1alpha1.json
pkg/data/schemas/json/test-chainsaw-v1alpha1.json
pkg/engine/operations/command/operation.go
pkg/engine/operations/script/operation.go
testdata/e2e/examples/script-env/chainsaw-test.yaml
website/docs/reference/apis/chainsaw.v1alpha1.md

Add skip command output support.
Fixes https://github.com/kyverno/chainsaw/issues/2134

feat: add skip command output support

---

pkg/engine/context/context.go
pkg/runner/processors/context.go
pkg/runner/processors/step.go
pkg/runner/processors/step_test.go
pkg/runner/processors/test.go
pkg/runner/processors/test_test.go
pkg/runner/processors/tests.go
pkg/runner/run.go

Add skip delete in test context.

refactor: add skip delete in test context

---

pkg/engine/context/context.go
pkg/runner/processors/context.go
pkg/runner/processors/step.go
pkg/runner/processors/step_test.go
pkg/runner/processors/test.go
pkg/runner/processors/test_test.go
pkg/runner/processors/tests.go
pkg/runner/run.go

Add deletion propagation in test context.

refactor: add deletion propagation in test context

---

pkg/engine/context/context.go
pkg/runner/processors/context.go
pkg/runner/processors/step.go
pkg/runner/processors/step_test.go
pkg/runner/processors/test.go
pkg/runner/processors/test_test.go
pkg/runner/processors/tests.go
pkg/runner/run.go

Add delay before cleanup in test context.

refactor: add delay before cleanup in test context

---

pkg/engine/context/context.go
pkg/runner/processors/context.go
pkg/runner/processors/step.go
pkg/runner/processors/step_test.go
pkg/runner/processors/test.go
pkg/runner/processors/test_test.go
pkg/runner/processors/tests.go
pkg/runner/run.go

Add termination grace in test context.

refactor: add termination grace in test context

---

pkg/engine/context/context.go
pkg/runner/processors/context.go
pkg/runner/processors/step.go
pkg/runner/processors/step_test.go
pkg/runner/processors/test.go
pkg/runner/processors/test_test.go
pkg/runner/processors/tests.go
pkg/runner/run.go

refactor: add catch in test context

---

website/docs/quick-start/resource-templating.md

I went trough the getting started and noticed a missing `try` block. 
-
- 
-

chore(docs): add required try block

---

pkg/engine/context/context.go
pkg/runner/processors/tests.go
pkg/runner/run.go

Add fail fast in test context.

refactor: add fail fast in test context

---

pkg/engine/context/context.go
pkg/runner/processors/tests.go
pkg/runner/run.go

Add full name in test context.

refactor: add full name in test context

---

pkg/runner/processors/context.go
pkg/runner/processors/step.go
pkg/runner/processors/test.go
pkg/runner/processors/tests.go
pkg/runner/run.go

refactor: context setup

---

pkg/runner/processors/tests.go
pkg/runner/processors/tests_test.go
pkg/runner/run.go

Remove config from processors.

refactor: remove config from processors

---

pkg/runner/failer/failer.go
pkg/runner/processors/step.go
pkg/runner/processors/step_test.go
pkg/runner/test.go
pkg/runner/tests.go
pkg/testing/context.go

Don't use FailNow and SkipNow.

refactor: don't use FailNow and SkipNow

---

pkg/runner/failer/failer.go
pkg/runner/processors/context.go
pkg/runner/processors/step.go
pkg/runner/test.go
pkg/runner/tests.go

refactor: shrink failer interface

---

pkg/engine/operations/sleep/operation.go
pkg/engine/operations/sleep/operation_test.go
pkg/runner/operations/apply.go
pkg/runner/operations/assert.go
pkg/runner/operations/command.go
pkg/runner/operations/create.go
pkg/runner/operations/delete.go
pkg/runner/operations/describe.go
pkg/runner/operations/error.go
pkg/runner/operations/factory.go
pkg/runner/operations/get.go
pkg/runner/operations/helpers.go
pkg/runner/operations/operation.go
pkg/runner/operations/operation_test.go
pkg/runner/operations/patch.go
pkg/runner/operations/podlogs.go
pkg/runner/operations/proxy.go
pkg/runner/operations/script.go
pkg/runner/operations/sleep.go
pkg/runner/operations/sleep_test.go
pkg/runner/operations/update.go
pkg/runner/operations/wait.go
pkg/runner/operations/wait_test.go
pkg/runner/runner.go

refactor: introduce action factory

---

.github/workflows/lint.yaml
.golangci.yml

fix: golang ci lint

---

website/jp/examples/parse_json.md
website/jp/examples/to_boolean.md

fix: docs codegen

---

pkg/runner/runner.go

fix: deletion order

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/general-question.yaml
.release-notes/main.md
.release-notes/v0.2.13.md

release: v0.2.13

---

website/docs/step/catch.md
website/docs/step/cleanup.md
website/docs/step/finally.md
website/docs/step/try.md

Update allowed operations in try.

docs: update allowed operations in try
