- .github/workflows/tests.yaml
- pkg/client/client.go
- pkg/runner/runner.go
- testdata/tests/configmap.yaml
Add pet namespace if necessary.
> fix: add pet namespace if necessary

- website/docs/tests/with-test.md
With respect to issue #389, this PR suggests to add a short comment about the enforced usage of the specific `chainsaw-test.yam` filename at the beginning of the [Test based syntax](https://kyverno.github.io/chainsaw/tests/with-test/) page until you consider adding a command line flag for this purpose.
> Add a note to mention hard-coded test name

- pkg/runner/processors/step.go
Add delay when creating pods/deployments.
Workaround to prevent cleanup to take too long.
> fix: add delay when creating pods/deployments

- .release-notes/main.md
- pkg/commands/kuttl/migrate/command.go
Fixed a kuttl migration failure in case of unsupported name.
> fix: kuttl migration failure in case of unsupported name

- .release-notes/main.md
- pkg/commands/kuttl/migrate/command.go
Fixed invalid name in kuttl migrate command.
> fix: invalid name in kuttl migrate command

- pkg/commands/kuttl/migrate/command.go
Force lower case name in kuttl migrate.
> fix: force lower case name in kuttl migrate

- .release-notes/main.md
Update release notes for `v0.0.7`.
Fixes #515
> chore: update release notes for `v0.0.7`

- pkg/apis/v1alpha1/timeouts.go
- pkg/runner/processors/step.go
- pkg/runner/processors/test.go
- pkg/runner/timeout/timeout.go
Refactor timeouts management (part 2).
Combined timeouts are computed only once per test/step.
> refactor: timeouts management (part 2)

- .release-notes/main.md
- pkg/commands/docs/options.go
- pkg/commands/generate/docs/command.go
- website/docs/commands/chainsaw_generate_docs.md
Add `--readme-file` flag to generate docs command.
> feat: add --readme-file flag to generate docs command

- website/docs/examples/test-output.md
- website/mkdocs.yaml
Signed-off-by: chipzoller <chipzoller@gmail.com>
Adds a page to the list of examples illustrating how to test for command outputs.
Closes #755
Adds a page to the list of examples illustrating how to test for command outputs.
> Add example page on testing outputs

- pkg/commands/migrate/kuttl/config/command.go
- pkg/commands/migrate/kuttl/tests/command.go
- testdata/commands/migrate/kuttl/tests/out.txt
- testdata/kuttl/chainsaw-test.yaml
Fix `chainsaw migrate kuttl tests ...` commands applied last instead of first.
This PR also adds support for `kuttl.dev/v1` and only splits files when necessary.
> fix: migrate kuttl commands are applied last instead of first

- ADOPTERS.md
Adds the [skiperator](https://github.com/kartverket/skiperator) project by the [Norwegian Mapping Authority](https://www.kartverket.no/en) to ADOPTERS.md.
> chore: add the Norwegian Mapping Authority as a user

- .release-notes/main.md
- pkg/commands/migrate/tests/command.go
Do not apply kuttl migration if already migrated.
> fix: do not apply kuttl migration if already migrated

- ADOPTERS.md
We just started adopting Chainsaw in our [main repo](https://github.com/keptn/lifecycle-toolkit/tree/main/test/chainsaw), we recently voted to abandon Kuttl in favor of it.
https://github.com/keptn/lifecycle-toolkit/issues/2949#issuecomment-1931643542 
Many thanks to @eddycharly for helping us 🚀
> Add Keptn to ADOPTERS.md

- .github/workflows/tests.yaml
Separate unit tests from codecov upload
> fix: separate unit tests from codecov upload

- website/docs/operations/create.md
Fix typo 
Fixes : https://github.com/kyverno/chainsaw/issues/906
Add ```
> docs: fix typo in docs

- pkg/commands/build/docs/docs.tmpl
- testdata/e2e/examples/patch/README.md
Add missing operations in build docs.
> fix: missing operations in build docs

- pkg/commands/assert/command.go
- pkg/commands/assert/command_test.go
- pkg/utils/reader/mockstdin.go
- testdata/commands/assert/assert.yaml
- testdata/commands/assert/help.txt
- website/docs/commands/chainsaw_assert.md
Add a flag `--file` and short `-f` while supporting the current approach of accepting files.
Fixes https://github.com/kyverno/chainsaw/issues/878
> feat(commands): accept stdin in assert cmd

- pkg/utils/diff/diff.go
Preserve apiVersion and kind when diffing.
> fix: preserve apiVersion and kind when diffing

- .release-notes/main.md
- pkg/report/report.go
don't put  double extension on a filename
Fixes https://github.com/kyverno/chainsaw/issues/930
> fix(report): report path and prevent double extension on file name

- .crds/chainsaw.kyverno.io_tests.yaml
- .crds/chainsaw.kyverno.io_teststeps.yaml
- .schemas/json/test-chainsaw-v1alpha1.json
- pkg/apis/v1alpha1/binding.go
- pkg/apis/v1alpha1/command.go
- pkg/apis/v1alpha1/script.go
- pkg/apis/v1alpha1/zz_generated.deepcopy.go
- pkg/data/crds/chainsaw.kyverno.io_tests.yaml
- pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
- pkg/data/schemas/json/test-chainsaw-v1alpha1.json
- pkg/runner/operations/command/operation.go
- pkg/runner/operations/internal/env.go
- pkg/runner/operations/script/operation.go
- pkg/runner/processors/bindings.go
- testdata/e2e/examples/CATALOG.md
- testdata/e2e/examples/script-env/README.md
- testdata/e2e/examples/script-env/chainsaw-test.yaml
- website/docs/apis/chainsaw.v1alpha1.md
Add env vars support in command and script.
Fixes #953
> feat: add env vars support in command and script

- ADOPTERS.md
Adds Tempo Operator to the list of adopters of Chainsaw. 
https://github.com/grafana/tempo-operator/pull/786
- [ x] I have read the [contributing guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md).
- [ x] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and followed the process including adding proof manifests to this PR.
> chore: Add Tempo Operator to the adopters list.

- .goreleaser.yaml
Fix base image for ko in goreleaser config.
Potential fix for #821
> fix: base image for ko in goreleaser config

- pkg/runner/functions/k8s.go
- pkg/runner/functions/k8s_test.go
Fix `jpKubernetesExists` not setting apiVersion/kind.
> fix: jpKubernetesExists not setting apiVersion/kind

- pkg/runner/kubectl/describe.go
- pkg/runner/processors/cleaner_test.go
- pkg/runner/processors/operation.go
- pkg/runner/processors/operation_test.go
- pkg/runner/processors/step.go
Introduce lazy operations.
This is needed when the content of the operation itself cannot be determined until it should execute.
> feat: introduce lazy operations

- pkg/values/load_test.go
- testdata/values/invalid.yaml
- testdata/values/values-1.yaml
- testdata/values/values-2.yaml
Add unit tests for values package.
Fixes #1046
> chore: add unit tests for values package

- codecov.yml
Ignore testing package in codecov.
> chore: ignore testing package in codecov

- pkg/commands/build/docs/docs.tmpl
- testdata/e2e/examples/wait/README.md
- testdata/e2e/examples/wait/chainsaw-test.yaml
Add missing operations in build docs command and support test level catch.
> fix: add missing operations in build docs command and support test level catch

- .release-notes/main.md
- pkg/discovery/step.go
Relax step file discovery regexp to allow more than 2 digits.
> fix: relax step file discovery regexp

- .release-notes/main.md
- pkg/runner/bindings/bindings.go
- pkg/runner/processors/operation.go
- pkg/runner/processors/step.go
- pkg/runner/processors/test.go
- pkg/runner/processors/tests.go
- testdata/e2e/examples/template/chainsaw-test.yaml
Fix test level bindings evaluated too early.
See https://github.com/linode/cluster-api-provider-linode/pull/181
> fix: test level bindings evaluated too early

- website/docs/bindings/outputs.md
This PR updates the documentation to correctly demonstrate how to parse JSON outputs for bindings, ensuring users implement the syntax accurately by using json_parse($stdout) for command outputs.
Slack link: [here](https://kubernetes.slack.com/archives/C067LUFL43U/p1710497221445859)
Enhancing the docs.
> chore: add json_parse to match in Outputs docs

- website/docs/overrides/home.html
Add missing adopters to the home page.
Fixes #1309
> chore: add missing adopters to the home page

- README.md
The `Getting Started` link in README is broken.
> docs: fixed broken link in README

- .release-notes/main.md
- website/apis/markdown/type.tpl
- website/docs/reference/apis/chainsaw.v1alpha1.md
- website/docs/reference/apis/chainsaw.v1alpha2.md
Remove code markers on titles in api reference documentation.
> docs: remove code markers on titles in api reference documentation

- Makefile
- go.mod
- pkg/commands/build/docs/command.go
- pkg/commands/test/command.go
- pkg/discovery/discovery.go
- pkg/discovery/discovery_test.go
- pkg/discovery/load.go
- pkg/discovery/load_test.go
- pkg/test/load.go
- pkg/test/load_test.go
- pkg/utils/yaml/yaml.go
- testdata/commands/test/help.txt
- testdata/e2e/examples/CATALOG.md
- testdata/e2e/examples/yaml-anchors/README.md
- testdata/e2e/examples/yaml-anchors/chainsaw-test.yaml
- website/docs/reference/commands/chainsaw_test.md
Fix yaml anchors processing.
At first sight [gopkg.in/yaml.v3](http://gopkg.in/yaml.v3) looks more correct, at least in this area :thinking_face:
Fixes #1275
> fix: yaml anchors processing

- website/docs/configuration/options/cleanup.md
The command in the docs doesn't exist, replaced by the correct one: `cleanup-delay`.
na
small docs change
- [ x] I have read the [contributing guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md).
> fix: parameter cleanup delay in docs

- .release-notes/main.md
- pkg/runner/processors/operation.go
- pkg/runner/processors/operation_test.go
- pkg/runner/processors/step.go
- pkg/runner/processors/tests.go
> refactor: more test context

- .release-notes/main.md
- pkg/runner/processors/step.go
> feat: support templating in files

- pkg/engine/bindings/bindings.go
- pkg/engine/kubectl/describe.go
- pkg/engine/kubectl/get.go
- pkg/engine/kubectl/logs.go
- pkg/engine/kubectl/mapping.go
- pkg/engine/kubectl/proxy.go
- pkg/engine/kubectl/wait.go
- pkg/expressions/parse.go
- pkg/expressions/string.go
- pkg/expressions/string_pointer.go
- pkg/expressions/string_pointer_test.go
- pkg/expressions/string_test.go
- pkg/mutate/expression.go
- pkg/mutate/parse.go
- pkg/runner/processors/step.go
Simplify string expressions management.
> feat: simplify string expressions management

- pkg/apis/v1alpha1/types.go
- pkg/runner/processors/step.go
Add expression method to get value.
> feat: add expression method to get value

- pkg/model/report.go
- pkg/report/json.go
- pkg/report/junit.go
- pkg/runner/processors/operation.go
- pkg/runner/processors/operation_test.go
- pkg/runner/processors/step.go
> feat: operation type to report

- .github/workflows/tests.yaml
- Makefile
- pkg/runner/processors/context.go
> fix: no-cluster option

- .vscode/launch.json
- pkg/commands/test/command.go
- testdata/commands/test/help.txt
- website/docs/reference/commands/chainsaw_test.md
Add sharding support.
Fixes #1066
> feat: add sharding support

- pkg/apis/compiler.go
- pkg/engine/bindings/bindings.go
- pkg/engine/bindings/bindings_test.go
- pkg/engine/checks/check.go
- pkg/engine/context/context.go
- pkg/engine/operations/apply/operation.go
- pkg/engine/operations/assert/operation.go
- pkg/engine/operations/command/operation.go
- pkg/engine/operations/create/operation.go
- pkg/engine/operations/delete/operation.go
- pkg/engine/operations/error/operation.go
- pkg/engine/operations/patch/operation.go
- pkg/engine/operations/script/operation.go
- pkg/engine/operations/update/operation.go
- pkg/engine/outputs/outputs_test.go
- pkg/engine/templating/resource_ref_test.go
- pkg/expressions/string_pointer_test.go
- pkg/expressions/string_test.go
- pkg/mutate/mutate_test.go
- pkg/runner/processors/step_test.go
- pkg/runner/processors/test_test.go
- pkg/runner/processors/tests_test.go
> feat: add cel support

- pkg/discovery/load.go
- testdata/e2e/examples/CATALOG.md
- testdata/e2e/examples/step-template-bindings/README.md
- testdata/e2e/examples/step-template-bindings/chainsaw-test.yaml
- testdata/e2e/examples/step-template-bindings/template.yaml
Fix step template bindings registered in  wrong order.
Fixes https://github.com/kyverno/chainsaw/issues/2133
> fix: step template bindings wrong order

- pkg/runner/context/context.go
- pkg/runner/operations/apply.go
- pkg/runner/operations/assert.go
- pkg/runner/operations/command.go
- pkg/runner/operations/create.go
- pkg/runner/operations/delete.go
- pkg/runner/operations/describe.go
- pkg/runner/operations/error.go
- pkg/runner/operations/factory.go
- pkg/runner/operations/get.go
- pkg/runner/operations/patch.go
- pkg/runner/operations/podlogs.go
- pkg/runner/operations/proxy.go
- pkg/runner/operations/script.go
- pkg/runner/operations/update.go
- pkg/runner/operations/wait.go
- pkg/runner/operations/wait_test.go
- pkg/runner/runner.go
- pkg/runner/step_test.go
Add namespacer in test context.
> refactor: add namespacer in test context

- .crds/chainsaw.kyverno.io_configurations.yaml
- .schemas/json/configuration-chainsaw-v1alpha1.json
- .schemas/json/configuration-chainsaw-v1alpha2.json
- pkg/apis/v1alpha1/configuration.go
- pkg/apis/v1alpha2/options.go
- pkg/commands/test/command.go
- pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
- pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
- pkg/data/schemas/json/configuration-chainsaw-v1alpha2.json
- testdata/commands/test/help.txt
- website/docs/configuration/options/report.md
- website/docs/reference/apis/chainsaw.v1alpha1.md
- website/docs/reference/apis/chainsaw.v1alpha2.md
- website/docs/reference/commands/chainsaw_test.md
There's a literal `JSON|XML...` in one comment, which then gets rendered in a Markdown table (which uses pipes for column separator) and all but the first element in this piped array is lost. See https://kyverno.github.io/chainsaw/0.2.3/configuration/options/report/ and https://kyverno.github.io/chainsaw/0.2.3/reference/apis/chainsaw.v1alpha2/#chainsaw-kyverno-io-v1alpha2-Report
None
Swapping pipes for slashes, the implied meaning stays the same and we don't have to worry about rendering issues.
I ran `make codegen-api-docs` before submitting this change.
Supersedes #2350
> docs: Do not use pipes in comments, they won't be rendered in Markdown tables

- .github/workflows/lint.yaml
- .golangci.yml
- pkg/commands/docs/utils.go
- pkg/commands/migrate/kuttl/tests/command.go
- pkg/discovery/load.go
- pkg/engine/kubectl/wait.go
- pkg/runner/runner.go
- pkg/utils/rest/config.go
This updates golangci-lint to v2 to keep dependencies up to date and take advantage of updated linters. This will ensure that the code remains easy to consume and up to date with latest best practices per the various linters configured.
N/A
Update golangci-lint from v1 syntax to v2 via `golangci-lint migrate` and address any lints that are picked up by updated linters.
This is a pretty small change and can be confirmed by running `golangci-lint run -v ./...` where golangci-lint is of version `v2.X` and you can verify that there are no lints that need addressed.
> chore(deps): bump golangci-lint to v2

- pkg/runner/runner.go
Use SkipNow instead of Skip to prevent log line.
> fix: use SkipNow instead of Skip to prevent log line

- .goreleaser.yaml
Fix kos config in goreleaser (https://goreleaser.com/deprecations/#kosrepository)
> fix: kos config in goreleaser
